//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAMOSA.SCPP.Client.View.Administrador.svcAlerta {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoAlerta", Namespace="Lamosa.SCPP.Common.Entities.ClassImpl")]
    [System.SerializableAttribute()]
    public partial class TipoAlerta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigAlerta", Namespace="Lamosa.SCPP.Common.Entities.ClassImpl")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.TipoAlerta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Alerta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Proceso))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Frecuencia))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Planta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Destinatario))]
    public partial class ConfigAlerta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private object AlertaField;
        
        private string ClaveField;
        
        private string ClaveCalidadField;
        
        private int CodColorField;
        
        private int CodDefectoField;
        
        private int CodLimiteMaximoField;
        
        private int CodLimiteMinimoField;
        
        private int CodOperadorField;
        
        private int CodTipoArticuloField;
        
        private int CodTurnoField;
        
        private int CodZonaDefectoField;
        
        private int CodigoField;
        
        private string DescripcionField;
        
        private int MaquinaField;
        
        private int ModeloField;
        
        private object PlantaField;
        
        private object ProcesoField;
        
        private object TipoDefectoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object Alerta {
            get {
                return this.AlertaField;
            }
            set {
                if ((object.ReferenceEquals(this.AlertaField, value) != true)) {
                    this.AlertaField = value;
                    this.RaisePropertyChanged("Alerta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ClaveCalidad {
            get {
                return this.ClaveCalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveCalidadField, value) != true)) {
                    this.ClaveCalidadField = value;
                    this.RaisePropertyChanged("ClaveCalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodColor {
            get {
                return this.CodColorField;
            }
            set {
                if ((this.CodColorField.Equals(value) != true)) {
                    this.CodColorField = value;
                    this.RaisePropertyChanged("CodColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodDefecto {
            get {
                return this.CodDefectoField;
            }
            set {
                if ((this.CodDefectoField.Equals(value) != true)) {
                    this.CodDefectoField = value;
                    this.RaisePropertyChanged("CodDefecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodLimiteMaximo {
            get {
                return this.CodLimiteMaximoField;
            }
            set {
                if ((this.CodLimiteMaximoField.Equals(value) != true)) {
                    this.CodLimiteMaximoField = value;
                    this.RaisePropertyChanged("CodLimiteMaximo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodLimiteMinimo {
            get {
                return this.CodLimiteMinimoField;
            }
            set {
                if ((this.CodLimiteMinimoField.Equals(value) != true)) {
                    this.CodLimiteMinimoField = value;
                    this.RaisePropertyChanged("CodLimiteMinimo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodOperador {
            get {
                return this.CodOperadorField;
            }
            set {
                if ((this.CodOperadorField.Equals(value) != true)) {
                    this.CodOperadorField = value;
                    this.RaisePropertyChanged("CodOperador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodTipoArticulo {
            get {
                return this.CodTipoArticuloField;
            }
            set {
                if ((this.CodTipoArticuloField.Equals(value) != true)) {
                    this.CodTipoArticuloField = value;
                    this.RaisePropertyChanged("CodTipoArticulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodTurno {
            get {
                return this.CodTurnoField;
            }
            set {
                if ((this.CodTurnoField.Equals(value) != true)) {
                    this.CodTurnoField = value;
                    this.RaisePropertyChanged("CodTurno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodZonaDefecto {
            get {
                return this.CodZonaDefectoField;
            }
            set {
                if ((this.CodZonaDefectoField.Equals(value) != true)) {
                    this.CodZonaDefectoField = value;
                    this.RaisePropertyChanged("CodZonaDefecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Maquina {
            get {
                return this.MaquinaField;
            }
            set {
                if ((this.MaquinaField.Equals(value) != true)) {
                    this.MaquinaField = value;
                    this.RaisePropertyChanged("Maquina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((this.ModeloField.Equals(value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object Planta {
            get {
                return this.PlantaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlantaField, value) != true)) {
                    this.PlantaField = value;
                    this.RaisePropertyChanged("Planta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object Proceso {
            get {
                return this.ProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcesoField, value) != true)) {
                    this.ProcesoField = value;
                    this.RaisePropertyChanged("Proceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object TipoDefecto {
            get {
                return this.TipoDefectoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDefectoField, value) != true)) {
                    this.TipoDefectoField = value;
                    this.RaisePropertyChanged("TipoDefecto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alerta", Namespace="Lamosa.SCPP.Common.Entities.ClassImpl")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.TipoAlerta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.ConfigAlerta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Proceso))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Frecuencia))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Planta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Destinatario))]
    public partial class Alerta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsuntoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<object> DestinatariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object FrecuenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object TipoAlertaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Asunto {
            get {
                return this.AsuntoField;
            }
            set {
                if ((object.ReferenceEquals(this.AsuntoField, value) != true)) {
                    this.AsuntoField = value;
                    this.RaisePropertyChanged("Asunto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<object> Destinatarios {
            get {
                return this.DestinatariosField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinatariosField, value) != true)) {
                    this.DestinatariosField = value;
                    this.RaisePropertyChanged("Destinatarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Frecuencia {
            get {
                return this.FrecuenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.FrecuenciaField, value) != true)) {
                    this.FrecuenciaField = value;
                    this.RaisePropertyChanged("Frecuencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object TipoAlerta {
            get {
                return this.TipoAlertaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoAlertaField, value) != true)) {
                    this.TipoAlertaField = value;
                    this.RaisePropertyChanged("TipoAlerta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proceso", Namespace="Lamosa.SCPP.Common.Entities.ClassImpl")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.TipoAlerta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.ConfigAlerta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Alerta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Frecuencia))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Planta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Destinatario))]
    public partial class Proceso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClaveField;
        
        private int CodigoField;
        
        private string DescripcionField;
        
        private object TipoProcesoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object TipoProceso {
            get {
                return this.TipoProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoProcesoField, value) != true)) {
                    this.TipoProcesoField = value;
                    this.RaisePropertyChanged("TipoProceso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Frecuencia", Namespace="Lamosa.SCPP.Common.Entities.ClassImpl")]
    [System.SerializableAttribute()]
    public partial class Frecuencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Planta", Namespace="Lamosa.SCPP.Common.Entities.ClassImpl")]
    [System.SerializableAttribute()]
    public partial class Planta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClaveField;
        
        private int CodigoField;
        
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Destinatario", Namespace="Lamosa.SCPP.Common.Entities.ClassImpl")]
    [System.SerializableAttribute()]
    public partial class Destinatario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClaveField;
        
        private int CodigoField;
        
        private string CorreoField;
        
        private string DescripcionField;
        
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Lamosa.SCPP.ServiceManager.Interfaces", ConfigurationName="svcAlerta.IAlertaServiceManager")]
    public interface IAlertaServiceManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="Lamosa.SCPP.ServiceManager.Interfaces/IAlertaServiceManager/ObtenerAlerta", ReplyAction="Lamosa.SCPP.ServiceManager.Interfaces/IAlertaServiceManager/ObtenerAlertaResponse" +
            "")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.TipoAlerta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.ConfigAlerta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Alerta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Proceso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Frecuencia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Planta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Destinatario))]
        System.Collections.Generic.List<object> ObtenerAlerta(object alerta);
        
        [System.ServiceModel.OperationContractAttribute(Action="Lamosa.SCPP.ServiceManager.Interfaces/IAlertaServiceManager/ObtenerConfigAlerta", ReplyAction="Lamosa.SCPP.ServiceManager.Interfaces/IAlertaServiceManager/ObtenerConfigAlertaRe" +
            "sponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.TipoAlerta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.ConfigAlerta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Alerta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Proceso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Frecuencia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Planta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Destinatario))]
        System.Collections.Generic.List<object> ObtenerConfigAlerta(object alerta);
        
        [System.ServiceModel.OperationContractAttribute(Action="Lamosa.SCPP.ServiceManager.Interfaces/IAlertaServiceManager/ObtenerDestinatario", ReplyAction="Lamosa.SCPP.ServiceManager.Interfaces/IAlertaServiceManager/ObtenerDestinatarioRe" +
            "sponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.TipoAlerta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.ConfigAlerta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Alerta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Proceso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Frecuencia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Planta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Destinatario))]
        System.Collections.Generic.List<object> ObtenerDestinatario(object alerta);
        
        [System.ServiceModel.OperationContractAttribute(Action="Lamosa.SCPP.ServiceManager.Interfaces/IAlertaServiceManager/Eliminar", ReplyAction="Lamosa.SCPP.ServiceManager.Interfaces/IAlertaServiceManager/EliminarResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.TipoAlerta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.ConfigAlerta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Alerta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Proceso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Frecuencia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Planta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LAMOSA.SCPP.Client.View.Administrador.svcAlerta.Destinatario))]
        bool Eliminar(object alerta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IAlertaServiceManagerChannel : LAMOSA.SCPP.Client.View.Administrador.svcAlerta.IAlertaServiceManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AlertaServiceManagerClient : System.ServiceModel.ClientBase<LAMOSA.SCPP.Client.View.Administrador.svcAlerta.IAlertaServiceManager>, LAMOSA.SCPP.Client.View.Administrador.svcAlerta.IAlertaServiceManager {
        
        public AlertaServiceManagerClient() {
        }
        
        public AlertaServiceManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlertaServiceManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlertaServiceManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlertaServiceManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<object> ObtenerAlerta(object alerta) {
            return base.Channel.ObtenerAlerta(alerta);
        }
        
        public System.Collections.Generic.List<object> ObtenerConfigAlerta(object alerta) {
            return base.Channel.ObtenerConfigAlerta(alerta);
        }
        
        public System.Collections.Generic.List<object> ObtenerDestinatario(object alerta) {
            return base.Channel.ObtenerDestinatario(alerta);
        }
        
        public bool Eliminar(object alerta) {
            return base.Channel.Eliminar(alerta);
        }
    }
}
