//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAMOSA.SCPP.Client.View.Administrador.svcCapacidadProduccion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Lamosa.SCPP.ServiceManager.Interfaces", ConfigurationName="svcCapacidadProduccion.ICapacidadProduccionServiceManager")]
    public interface ICapacidadProduccionServiceManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="Lamosa.SCPP.ServiceManager.Interfaces/ICapacidadProduccionServiceManager/ObtenerC" +
            "apacidadProduccion", ReplyAction="Lamosa.SCPP.ServiceManager.Interfaces/ICapacidadProduccionServiceManager/ObtenerC" +
            "apacidadProduccionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
        System.Collections.Generic.List<object> ObtenerCapacidadProduccion(object cpCapacidadProduccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="Lamosa.SCPP.ServiceManager.Interfaces/ICapacidadProduccionServiceManager/ObtenerA" +
            "vanceAcumulado", ReplyAction="Lamosa.SCPP.ServiceManager.Interfaces/ICapacidadProduccionServiceManager/ObtenerA" +
            "vanceAcumuladoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
        System.Collections.Generic.List<object> ObtenerAvanceAcumulado(object aaAvanceAcumulado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICapacidadProduccionServiceManagerChannel : LAMOSA.SCPP.Client.View.Administrador.svcCapacidadProduccion.ICapacidadProduccionServiceManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CapacidadProduccionServiceManagerClient : System.ServiceModel.ClientBase<LAMOSA.SCPP.Client.View.Administrador.svcCapacidadProduccion.ICapacidadProduccionServiceManager>, LAMOSA.SCPP.Client.View.Administrador.svcCapacidadProduccion.ICapacidadProduccionServiceManager {
        
        public CapacidadProduccionServiceManagerClient() {
        }
        
        public CapacidadProduccionServiceManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CapacidadProduccionServiceManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CapacidadProduccionServiceManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CapacidadProduccionServiceManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<object> ObtenerCapacidadProduccion(object cpCapacidadProduccion) {
            return base.Channel.ObtenerCapacidadProduccion(cpCapacidadProduccion);
        }
        
        public System.Collections.Generic.List<object> ObtenerAvanceAcumulado(object aaAvanceAcumulado) {
            return base.Channel.ObtenerAvanceAcumulado(aaAvanceAcumulado);
        }
    }
}
