//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAMOSA.SCPP.Client.View.Administrador.svcSCPP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svcSCPP.ISCPP")]
    public interface ISCPP {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/DesbloquearUsuario", ReplyAction="http://tempuri.org/ISCPP/DesbloquearUsuarioResponse")]
        bool DesbloquearUsuario(int CodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/GuardarConfigBanco", ReplyAction="http://tempuri.org/ISCPP/GuardarConfigBancoResponse")]
        int GuardarConfigBanco(LAMOSA.SCPP.Server.BusinessEntity.ConfigBancoResgistro CB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/GuardaRutaProceso", ReplyAction="http://tempuri.org/ISCPP/GuardaRutaProcesoResponse")]
        LAMOSA.SCPP.Server.BusinessEntity.RutaProceso GuardaRutaProceso(LAMOSA.SCPP.Server.BusinessEntity.RutaProceso RutaProceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/GuardaInventario", ReplyAction="http://tempuri.org/ISCPP/GuardaInventarioResponse")]
        void GuardaInventario(LAMOSA.SCPP.Server.BusinessEntity.Inventario inv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/GuardarMetasProd", ReplyAction="http://tempuri.org/ISCPP/GuardarMetasProdResponse")]
        void GuardarMetasProd(LAMOSA.SCPP.Server.BusinessEntity.MetasProd MP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/IniciarTerminarInventario", ReplyAction="http://tempuri.org/ISCPP/IniciarTerminarInventarioResponse")]
        void IniciarTerminarInventario(int codInventario, bool enProceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/EliminaRutaProceso", ReplyAction="http://tempuri.org/ISCPP/EliminaRutaProcesoResponse")]
        LAMOSA.SCPP.Server.BusinessEntity.RutaProceso EliminaRutaProceso(LAMOSA.SCPP.Server.BusinessEntity.RutaProceso RutaProceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/EliminaConfigBanco", ReplyAction="http://tempuri.org/ISCPP/EliminaConfigBancoResponse")]
        LAMOSA.SCPP.Server.BusinessEntity.ConfigBancos EliminaConfigBanco(LAMOSA.SCPP.Server.BusinessEntity.ConfigBancos CB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/EliminaUsuario", ReplyAction="http://tempuri.org/ISCPP/EliminaUsuarioResponse")]
        LAMOSA.SCPP.Server.BusinessEntity.Usuario EliminaUsuario(LAMOSA.SCPP.Server.BusinessEntity.Usuario U);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/EliminaTurno", ReplyAction="http://tempuri.org/ISCPP/EliminaTurnoResponse")]
        void EliminaTurno(int codTurno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/EliminaRol", ReplyAction="http://tempuri.org/ISCPP/EliminaRolResponse")]
        void EliminaRol(int codRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/EliminaPrueba", ReplyAction="http://tempuri.org/ISCPP/EliminaPruebaResponse")]
        void EliminaPrueba(int CodPrueba);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/AutorizaConfigBanco", ReplyAction="http://tempuri.org/ISCPP/AutorizaConfigBancoResponse")]
        void AutorizaConfigBanco(LAMOSA.SCPP.Server.BusinessEntity.ConfigBancos AU);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/AutorizaCondicionEsmalte", ReplyAction="http://tempuri.org/ISCPP/AutorizaCondicionEsmalteResponse")]
        void AutorizaCondicionEsmalte(LAMOSA.SCPP.Server.BusinessEntity.CondicionEsmalteAutoriza AC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/AutorizaCondicionPasta", ReplyAction="http://tempuri.org/ISCPP/AutorizaCondicionPastaResponse")]
        void AutorizaCondicionPasta(LAMOSA.SCPP.Server.BusinessEntity.CondicionPastaAutoriza AC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/AutorizaCondicionOperacion", ReplyAction="http://tempuri.org/ISCPP/AutorizaCondicionOperacionResponse")]
        void AutorizaCondicionOperacion(LAMOSA.SCPP.Server.BusinessEntity.CondicionOperacionAutoriza AC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerCodigoBarras", ReplyAction="http://tempuri.org/ISCPP/ObtenerCodigoBarrasResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerCodigoBarras(int planta, int centroTrabajo, int banco, int empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/CambiarContrasena", ReplyAction="http://tempuri.org/ISCPP/CambiarContrasenaResponse")]
        LAMOSA.SCPP.Server.BusinessEntity.ContrasenaC CambiarContrasena(LAMOSA.SCPP.Server.BusinessEntity.ContrasenaC Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/CambiarContrasenaLogin", ReplyAction="http://tempuri.org/ISCPP/CambiarContrasenaLoginResponse")]
        LAMOSA.SCPP.Server.BusinessEntity.ContrasenaL CambiarContrasenaLogin(LAMOSA.SCPP.Server.BusinessEntity.ContrasenaL Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerInfoDashboard", ReplyAction="http://tempuri.org/ISCPP/ObtenerInfoDashboardResponse")]
        System.Data.DataSet ObtenerInfoDashboard(int iCodPlanta, int iRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerKardexExportar", ReplyAction="http://tempuri.org/ISCPP/ObtenerKardexExportarResponse")]
        System.Data.DataSet ObtenerKardexExportar(int iCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerHornoClasificado", ReplyAction="http://tempuri.org/ISCPP/ObtenerHornoClasificadoResponse")]
        System.Collections.Generic.List<LAMOSA.SCPP.Server.BusinessEntity.Maquina> ObtenerHornoClasificado(int iPlanta, int iProceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ExisteSKU", ReplyAction="http://tempuri.org/ISCPP/ExisteSKUResponse")]
        int ExisteSKU(string sku);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/InsertarPiezaReemplazo", ReplyAction="http://tempuri.org/ISCPP/InsertarPiezaReemplazoResponse")]
        bool InsertarPiezaReemplazo(int iCodPieza, int iCodProcesoPiezaReem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerAlerta", ReplyAction="http://tempuri.org/ISCPP/ObtenerAlertaResponse")]
        System.Data.DataTable ObtenerAlerta(int iCodigoAlerta, int iCodigoTipoAlerta, int iCodigoPlanta, int iCodigoProceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerAlertaPlanta", ReplyAction="http://tempuri.org/ISCPP/ObtenerAlertaPlantaResponse")]
        System.Data.DataTable ObtenerAlertaPlanta(int iCodigoAlerta, int iCodigoTipoAlerta, int iCodigoPlanta, int iCodigoProceso, int iCodigoOperador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerPiezasConResidencia", ReplyAction="http://tempuri.org/ISCPP/ObtenerPiezasConResidenciaResponse")]
        System.Data.DataTable ObtenerPiezasConResidencia(int iCodigoAlerta, int iCodigoPlanta, int iCodigoProceso, int iCodigoTipoArticulo, int iCodigoArticulo, int iCodigoMaquina, int iCodigoColor, int iCodigoEmpleado, int iCodigoTurno, int iDiasResidencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/PiezaBajaPorResidencia", ReplyAction="http://tempuri.org/ISCPP/PiezaBajaPorResidenciaResponse")]
        bool PiezaBajaPorResidencia(System.Data.DataTable dtPiezaParaBaja, int iCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerPiezasBajaResidencia", ReplyAction="http://tempuri.org/ISCPP/ObtenerPiezasBajaResidenciaResponse")]
        System.Data.DataTable ObtenerPiezasBajaResidencia(int iCodigoAlerta, int iCodigoPlanta, int iCodigoProceso, int iCodigoTipoArticulo, int iCodigoArticulo, int iCodigoMaquina, int iCodigoColor, int iCodigoEmpleado, int iCodigoTurno, int iDiasResidencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/PriezaReestablecerResidencia", ReplyAction="http://tempuri.org/ISCPP/PriezaReestablecerResidenciaResponse")]
        bool PriezaReestablecerResidencia(System.Data.DataTable dtPiezaParaBaja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerMensajeInicioSesion", ReplyAction="http://tempuri.org/ISCPP/ObtenerMensajeInicioSesionResponse")]
        string ObtenerMensajeInicioSesion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ValidarPoliticaContrasena", ReplyAction="http://tempuri.org/ISCPP/ValidarPoliticaContrasenaResponse")]
        bool ValidarPoliticaContrasena(string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/CambiarContrasenaUsuario", ReplyAction="http://tempuri.org/ISCPP/CambiarContrasenaUsuarioResponse")]
        string CambiarContrasenaUsuario(string sUsuario, string sContrasenaActual, string sContrasenaNueva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerMaquinaCbo", ReplyAction="http://tempuri.org/ISCPP/ObtenerMaquinaCboResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerMaquinaCbo(int codArea, int codCT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerMaquinas", ReplyAction="http://tempuri.org/ISCPP/ObtenerMaquinasResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerMaquinas(int codigoArea, int codigoCentroTrabajo, int codigoPlanta, int codigoProceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerMaquina", ReplyAction="http://tempuri.org/ISCPP/ObtenerMaquinaResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerMaquina(int codPlanta, int codProceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerPuesto", ReplyAction="http://tempuri.org/ISCPP/ObtenerPuestoResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerPuesto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerUsuarios", ReplyAction="http://tempuri.org/ISCPP/ObtenerUsuariosResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerUsuarios(int Planta, int Rol, string Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerEmpleadoBusqueda", ReplyAction="http://tempuri.org/ISCPP/ObtenerEmpleadoBusquedaResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerEmpleadoBusqueda(int CodEmpleado, string NombreEmpleado, int Rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerMFGEmpleado", ReplyAction="http://tempuri.org/ISCPP/ObtenerMFGEmpleadoResponse")]
        string ObtenerMFGEmpleado(int CodEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerCondicionEsmalte", ReplyAction="http://tempuri.org/ISCPP/ObtenerCondicionEsmalteResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerCondicionEsmalte(int CodPlanta, System.DateTime FechaInicio, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerCondicionOperacion", ReplyAction="http://tempuri.org/ISCPP/ObtenerCondicionOperacionResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerCondicionOperacion(int CodPlanta, int CodProceso, int CodArea, System.DateTime FechaInicio, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerCondicionPasta", ReplyAction="http://tempuri.org/ISCPP/ObtenerCondicionPastaResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerCondicionPasta(int CodPlanta, System.DateTime FechaInicio, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerCondicionPastaExportar", ReplyAction="http://tempuri.org/ISCPP/ObtenerCondicionPastaExportarResponse")]
        System.Data.DataTable ObtenerCondicionPastaExportar(int CodPlanta, System.DateTime FechaInicio, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerCondicionEsmalteExportar", ReplyAction="http://tempuri.org/ISCPP/ObtenerCondicionEsmalteExportarResponse")]
        System.Data.DataTable ObtenerCondicionEsmalteExportar(int CodPlanta, System.DateTime FechaInicio, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerConfiguracionBancoDetalle", ReplyAction="http://tempuri.org/ISCPP/ObtenerConfiguracionBancoDetalleResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerConfiguracionBancoDetalle(int CodConfigBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerConfiguracionBanco", ReplyAction="http://tempuri.org/ISCPP/ObtenerConfiguracionBancoResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerConfiguracionBanco(int planta, int ct, int maquina, int activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerInventarioEnProceso", ReplyAction="http://tempuri.org/ISCPP/ObtenerInventarioEnProcesoResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerInventarioEnProceso(int CodAlmacen, int CodPlanta, int CodProceso, int CodTipoArticulo, int CodArticulo, System.DateTime FechaInicio, System.DateTime FechaFin, int Opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerInventario", ReplyAction="http://tempuri.org/ISCPP/ObtenerInventarioResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerInventario(int CodPlanta, System.DateTime FechaInicio, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerPiezasReemplazo", ReplyAction="http://tempuri.org/ISCPP/ObtenerPiezasReemplazoResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerPiezasReemplazo(bool SinPiezasreemplazadas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerConfig", ReplyAction="http://tempuri.org/ISCPP/ObtenerConfigResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerConfig(int CodConfiguracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerRepCapInstalada", ReplyAction="http://tempuri.org/ISCPP/ObtenerRepCapInstaladaResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerRepCapInstalada(int Opcion, int Planta, int CT, int Banco, int TipoArt, int Molde);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerMetasProd", ReplyAction="http://tempuri.org/ISCPP/ObtenerMetasProdResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerMetasProd(int CodPlanta, System.DateTime FechaInicio, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerKardexProductoBusqueda", ReplyAction="http://tempuri.org/ISCPP/ObtenerKardexProductoBusquedaResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerKardexProductoBusqueda(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerKardexProducto", ReplyAction="http://tempuri.org/ISCPP/ObtenerKardexProductoResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerKardexProducto(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerKardexProductoDefecto", ReplyAction="http://tempuri.org/ISCPP/ObtenerKardexProductoDefectoResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerKardexProductoDefecto(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/GuardarPlanta", ReplyAction="http://tempuri.org/ISCPP/GuardarPlantaResponse")]
        void GuardarPlanta(LAMOSA.SCPP.Server.BusinessEntity.Planta Planta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/GuardarPrueba", ReplyAction="http://tempuri.org/ISCPP/GuardarPruebaResponse")]
        void GuardarPrueba(LAMOSA.SCPP.Server.BusinessEntity.Prueba Prueba, int iCodPlanta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/GuardarUsuario", ReplyAction="http://tempuri.org/ISCPP/GuardarUsuarioResponse")]
        LAMOSA.SCPP.Server.BusinessEntity.Usuario GuardarUsuario(LAMOSA.SCPP.Server.BusinessEntity.Usuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/GuardarTurno", ReplyAction="http://tempuri.org/ISCPP/GuardarTurnoResponse")]
        void GuardarTurno(LAMOSA.SCPP.Server.BusinessEntity.Turno Turno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/GuardarCondicionPasta", ReplyAction="http://tempuri.org/ISCPP/GuardarCondicionPastaResponse")]
        void GuardarCondicionPasta(LAMOSA.SCPP.Server.BusinessEntity.CondicionPasta CP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/GuardarCondicionOperacion", ReplyAction="http://tempuri.org/ISCPP/GuardarCondicionOperacionResponse")]
        void GuardarCondicionOperacion(LAMOSA.SCPP.Server.BusinessEntity.CondicionOperacionGuarda CO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/GuardaRol", ReplyAction="http://tempuri.org/ISCPP/GuardaRolResponse")]
        void GuardaRol(LAMOSA.SCPP.Server.BusinessEntity.rolplanta RolPlanta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/GuardarConfig", ReplyAction="http://tempuri.org/ISCPP/GuardarConfigResponse")]
        void GuardarConfig(LAMOSA.SCPP.Server.BusinessEntity.Configuracion Conf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/GuardarCondicionEsmalte", ReplyAction="http://tempuri.org/ISCPP/GuardarCondicionEsmalteResponse")]
        void GuardarCondicionEsmalte(LAMOSA.SCPP.Server.BusinessEntity.CondicionEsmalte CE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerTurnos", ReplyAction="http://tempuri.org/ISCPP/ObtenerTurnosResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerTurnos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerCalidades", ReplyAction="http://tempuri.org/ISCPP/ObtenerCalidadesResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerCalidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerCalidadesCbo", ReplyAction="http://tempuri.org/ISCPP/ObtenerCalidadesCboResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerCalidadesCbo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerPlantaCalidadCbo", ReplyAction="http://tempuri.org/ISCPP/ObtenerPlantaCalidadCboResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerPlantaCalidadCbo(int CodPlanta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerDefectosCbo", ReplyAction="http://tempuri.org/ISCPP/ObtenerDefectosCboResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerDefectosCbo(int CodProceso, int CodTipoDefecto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerZonaDefectoCbo", ReplyAction="http://tempuri.org/ISCPP/ObtenerZonaDefectoCboResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerZonaDefectoCbo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerColores", ReplyAction="http://tempuri.org/ISCPP/ObtenerColoresResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerColores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerArticulos", ReplyAction="http://tempuri.org/ISCPP/ObtenerArticulosResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerArticulos(LAMOSA.SCPP.Server.BusinessEntity.ArticuloPars articuloPars);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerArticulosCbo", ReplyAction="http://tempuri.org/ISCPP/ObtenerArticulosCboResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerArticulosCbo(int tipoArticulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerModelosCbo", ReplyAction="http://tempuri.org/ISCPP/ObtenerModelosCboResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerModelosCbo(int tipoArticulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerTiposArticuloCbo", ReplyAction="http://tempuri.org/ISCPP/ObtenerTiposArticuloCboResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerTiposArticuloCbo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerMoldesCbo", ReplyAction="http://tempuri.org/ISCPP/ObtenerMoldesCboResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerMoldesCbo(LAMOSA.SCPP.Server.BusinessEntity.ArticuloPars articuloPars);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerMoldes", ReplyAction="http://tempuri.org/ISCPP/ObtenerMoldesResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerMoldes(LAMOSA.SCPP.Server.BusinessEntity.ArticuloPars articuloPars);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/Login", ReplyAction="http://tempuri.org/ISCPP/LoginResponse")]
        LAMOSA.SCPP.Server.BusinessEntity.LoginUsuario Login(LAMOSA.SCPP.Server.BusinessEntity.LoginUsuario lu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerPruebas", ReplyAction="http://tempuri.org/ISCPP/ObtenerPruebasResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerPruebas(int Proceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerDefectos", ReplyAction="http://tempuri.org/ISCPP/ObtenerDefectosResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerDefectos(int CodProceso, int CodPlanta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerTiposDefecto", ReplyAction="http://tempuri.org/ISCPP/ObtenerTiposDefectoResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerTiposDefecto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerZonaDefecto", ReplyAction="http://tempuri.org/ISCPP/ObtenerZonaDefectoResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerZonaDefecto(int CodTipoArticulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerAlmacen", ReplyAction="http://tempuri.org/ISCPP/ObtenerAlmacenResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerAlmacen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerAlmacenCbo", ReplyAction="http://tempuri.org/ISCPP/ObtenerAlmacenCboResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerAlmacenCbo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerPlanta", ReplyAction="http://tempuri.org/ISCPP/ObtenerPlantaResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerPlanta(int Almacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerCentroTrabajo", ReplyAction="http://tempuri.org/ISCPP/ObtenerCentroTrabajoResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerCentroTrabajo(int Planta, int Proceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerCentroTrabajoCbo", ReplyAction="http://tempuri.org/ISCPP/ObtenerCentroTrabajoCboResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerCentroTrabajoCbo(int Planta, int Proceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerArea", ReplyAction="http://tempuri.org/ISCPP/ObtenerAreaResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerArea(int CT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerEstructuraPlanta", ReplyAction="http://tempuri.org/ISCPP/ObtenerEstructuraPlantaResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerEstructuraPlanta(int Planta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerProcesoCbo", ReplyAction="http://tempuri.org/ISCPP/ObtenerProcesoCboResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerProcesoCbo(int Planta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerProceso", ReplyAction="http://tempuri.org/ISCPP/ObtenerProcesoResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerProceso();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerRutaProceso", ReplyAction="http://tempuri.org/ISCPP/ObtenerRutaProcesoResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerRutaProceso(int Planta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerRol", ReplyAction="http://tempuri.org/ISCPP/ObtenerRolResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerRol();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerRolCbo", ReplyAction="http://tempuri.org/ISCPP/ObtenerRolCboResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerRolCbo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerEmpleado", ReplyAction="http://tempuri.org/ISCPP/ObtenerEmpleadoResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerEmpleado(int CodPlanta, int CodPuesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP/ObtenerPlantaCbo", ReplyAction="http://tempuri.org/ISCPP/ObtenerPlantaCboResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerPlantaCbo();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISCPPChannel : LAMOSA.SCPP.Client.View.Administrador.svcSCPP.ISCPP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SCPPClient : System.ServiceModel.ClientBase<LAMOSA.SCPP.Client.View.Administrador.svcSCPP.ISCPP>, LAMOSA.SCPP.Client.View.Administrador.svcSCPP.ISCPP {
        
        public SCPPClient() {
        }
        
        public SCPPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SCPPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCPPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCPPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool DesbloquearUsuario(int CodigoUsuario) {
            return base.Channel.DesbloquearUsuario(CodigoUsuario);
        }
        
        public int GuardarConfigBanco(LAMOSA.SCPP.Server.BusinessEntity.ConfigBancoResgistro CB) {
            return base.Channel.GuardarConfigBanco(CB);
        }
        
        public LAMOSA.SCPP.Server.BusinessEntity.RutaProceso GuardaRutaProceso(LAMOSA.SCPP.Server.BusinessEntity.RutaProceso RutaProceso) {
            return base.Channel.GuardaRutaProceso(RutaProceso);
        }
        
        public void GuardaInventario(LAMOSA.SCPP.Server.BusinessEntity.Inventario inv) {
            base.Channel.GuardaInventario(inv);
        }
        
        public void GuardarMetasProd(LAMOSA.SCPP.Server.BusinessEntity.MetasProd MP) {
            base.Channel.GuardarMetasProd(MP);
        }
        
        public void IniciarTerminarInventario(int codInventario, bool enProceso) {
            base.Channel.IniciarTerminarInventario(codInventario, enProceso);
        }
        
        public LAMOSA.SCPP.Server.BusinessEntity.RutaProceso EliminaRutaProceso(LAMOSA.SCPP.Server.BusinessEntity.RutaProceso RutaProceso) {
            return base.Channel.EliminaRutaProceso(RutaProceso);
        }
        
        public LAMOSA.SCPP.Server.BusinessEntity.ConfigBancos EliminaConfigBanco(LAMOSA.SCPP.Server.BusinessEntity.ConfigBancos CB) {
            return base.Channel.EliminaConfigBanco(CB);
        }
        
        public LAMOSA.SCPP.Server.BusinessEntity.Usuario EliminaUsuario(LAMOSA.SCPP.Server.BusinessEntity.Usuario U) {
            return base.Channel.EliminaUsuario(U);
        }
        
        public void EliminaTurno(int codTurno) {
            base.Channel.EliminaTurno(codTurno);
        }
        
        public void EliminaRol(int codRol) {
            base.Channel.EliminaRol(codRol);
        }
        
        public void EliminaPrueba(int CodPrueba) {
            base.Channel.EliminaPrueba(CodPrueba);
        }
        
        public void AutorizaConfigBanco(LAMOSA.SCPP.Server.BusinessEntity.ConfigBancos AU) {
            base.Channel.AutorizaConfigBanco(AU);
        }
        
        public void AutorizaCondicionEsmalte(LAMOSA.SCPP.Server.BusinessEntity.CondicionEsmalteAutoriza AC) {
            base.Channel.AutorizaCondicionEsmalte(AC);
        }
        
        public void AutorizaCondicionPasta(LAMOSA.SCPP.Server.BusinessEntity.CondicionPastaAutoriza AC) {
            base.Channel.AutorizaCondicionPasta(AC);
        }
        
        public void AutorizaCondicionOperacion(LAMOSA.SCPP.Server.BusinessEntity.CondicionOperacionAutoriza AC) {
            base.Channel.AutorizaCondicionOperacion(AC);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerCodigoBarras(int planta, int centroTrabajo, int banco, int empleado) {
            return base.Channel.ObtenerCodigoBarras(planta, centroTrabajo, banco, empleado);
        }
        
        public LAMOSA.SCPP.Server.BusinessEntity.ContrasenaC CambiarContrasena(LAMOSA.SCPP.Server.BusinessEntity.ContrasenaC Contrasena) {
            return base.Channel.CambiarContrasena(Contrasena);
        }
        
        public LAMOSA.SCPP.Server.BusinessEntity.ContrasenaL CambiarContrasenaLogin(LAMOSA.SCPP.Server.BusinessEntity.ContrasenaL Contrasena) {
            return base.Channel.CambiarContrasenaLogin(Contrasena);
        }
        
        public System.Data.DataSet ObtenerInfoDashboard(int iCodPlanta, int iRol) {
            return base.Channel.ObtenerInfoDashboard(iCodPlanta, iRol);
        }
        
        public System.Data.DataSet ObtenerKardexExportar(int iCodigo) {
            return base.Channel.ObtenerKardexExportar(iCodigo);
        }
        
        public System.Collections.Generic.List<LAMOSA.SCPP.Server.BusinessEntity.Maquina> ObtenerHornoClasificado(int iPlanta, int iProceso) {
            return base.Channel.ObtenerHornoClasificado(iPlanta, iProceso);
        }
        
        public int ExisteSKU(string sku) {
            return base.Channel.ExisteSKU(sku);
        }
        
        public bool InsertarPiezaReemplazo(int iCodPieza, int iCodProcesoPiezaReem) {
            return base.Channel.InsertarPiezaReemplazo(iCodPieza, iCodProcesoPiezaReem);
        }
        
        public System.Data.DataTable ObtenerAlerta(int iCodigoAlerta, int iCodigoTipoAlerta, int iCodigoPlanta, int iCodigoProceso) {
            return base.Channel.ObtenerAlerta(iCodigoAlerta, iCodigoTipoAlerta, iCodigoPlanta, iCodigoProceso);
        }
        
        public System.Data.DataTable ObtenerAlertaPlanta(int iCodigoAlerta, int iCodigoTipoAlerta, int iCodigoPlanta, int iCodigoProceso, int iCodigoOperador) {
            return base.Channel.ObtenerAlertaPlanta(iCodigoAlerta, iCodigoTipoAlerta, iCodigoPlanta, iCodigoProceso, iCodigoOperador);
        }
        
        public System.Data.DataTable ObtenerPiezasConResidencia(int iCodigoAlerta, int iCodigoPlanta, int iCodigoProceso, int iCodigoTipoArticulo, int iCodigoArticulo, int iCodigoMaquina, int iCodigoColor, int iCodigoEmpleado, int iCodigoTurno, int iDiasResidencia) {
            return base.Channel.ObtenerPiezasConResidencia(iCodigoAlerta, iCodigoPlanta, iCodigoProceso, iCodigoTipoArticulo, iCodigoArticulo, iCodigoMaquina, iCodigoColor, iCodigoEmpleado, iCodigoTurno, iDiasResidencia);
        }
        
        public bool PiezaBajaPorResidencia(System.Data.DataTable dtPiezaParaBaja, int iCodigoUsuario) {
            return base.Channel.PiezaBajaPorResidencia(dtPiezaParaBaja, iCodigoUsuario);
        }
        
        public System.Data.DataTable ObtenerPiezasBajaResidencia(int iCodigoAlerta, int iCodigoPlanta, int iCodigoProceso, int iCodigoTipoArticulo, int iCodigoArticulo, int iCodigoMaquina, int iCodigoColor, int iCodigoEmpleado, int iCodigoTurno, int iDiasResidencia) {
            return base.Channel.ObtenerPiezasBajaResidencia(iCodigoAlerta, iCodigoPlanta, iCodigoProceso, iCodigoTipoArticulo, iCodigoArticulo, iCodigoMaquina, iCodigoColor, iCodigoEmpleado, iCodigoTurno, iDiasResidencia);
        }
        
        public bool PriezaReestablecerResidencia(System.Data.DataTable dtPiezaParaBaja) {
            return base.Channel.PriezaReestablecerResidencia(dtPiezaParaBaja);
        }
        
        public string ObtenerMensajeInicioSesion() {
            return base.Channel.ObtenerMensajeInicioSesion();
        }
        
        public bool ValidarPoliticaContrasena(string contrasena) {
            return base.Channel.ValidarPoliticaContrasena(contrasena);
        }
        
        public string CambiarContrasenaUsuario(string sUsuario, string sContrasenaActual, string sContrasenaNueva) {
            return base.Channel.CambiarContrasenaUsuario(sUsuario, sContrasenaActual, sContrasenaNueva);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerMaquinaCbo(int codArea, int codCT) {
            return base.Channel.ObtenerMaquinaCbo(codArea, codCT);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerMaquinas(int codigoArea, int codigoCentroTrabajo, int codigoPlanta, int codigoProceso) {
            return base.Channel.ObtenerMaquinas(codigoArea, codigoCentroTrabajo, codigoPlanta, codigoProceso);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerMaquina(int codPlanta, int codProceso) {
            return base.Channel.ObtenerMaquina(codPlanta, codProceso);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerPuesto() {
            return base.Channel.ObtenerPuesto();
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerUsuarios(int Planta, int Rol, string Usuario) {
            return base.Channel.ObtenerUsuarios(Planta, Rol, Usuario);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerEmpleadoBusqueda(int CodEmpleado, string NombreEmpleado, int Rol) {
            return base.Channel.ObtenerEmpleadoBusqueda(CodEmpleado, NombreEmpleado, Rol);
        }
        
        public string ObtenerMFGEmpleado(int CodEmpleado) {
            return base.Channel.ObtenerMFGEmpleado(CodEmpleado);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerCondicionEsmalte(int CodPlanta, System.DateTime FechaInicio, System.DateTime FechaFin) {
            return base.Channel.ObtenerCondicionEsmalte(CodPlanta, FechaInicio, FechaFin);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerCondicionOperacion(int CodPlanta, int CodProceso, int CodArea, System.DateTime FechaInicio, System.DateTime FechaFin) {
            return base.Channel.ObtenerCondicionOperacion(CodPlanta, CodProceso, CodArea, FechaInicio, FechaFin);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerCondicionPasta(int CodPlanta, System.DateTime FechaInicio, System.DateTime FechaFin) {
            return base.Channel.ObtenerCondicionPasta(CodPlanta, FechaInicio, FechaFin);
        }
        
        public System.Data.DataTable ObtenerCondicionPastaExportar(int CodPlanta, System.DateTime FechaInicio, System.DateTime FechaFin) {
            return base.Channel.ObtenerCondicionPastaExportar(CodPlanta, FechaInicio, FechaFin);
        }
        
        public System.Data.DataTable ObtenerCondicionEsmalteExportar(int CodPlanta, System.DateTime FechaInicio, System.DateTime FechaFin) {
            return base.Channel.ObtenerCondicionEsmalteExportar(CodPlanta, FechaInicio, FechaFin);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerConfiguracionBancoDetalle(int CodConfigBanco) {
            return base.Channel.ObtenerConfiguracionBancoDetalle(CodConfigBanco);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerConfiguracionBanco(int planta, int ct, int maquina, int activo) {
            return base.Channel.ObtenerConfiguracionBanco(planta, ct, maquina, activo);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerInventarioEnProceso(int CodAlmacen, int CodPlanta, int CodProceso, int CodTipoArticulo, int CodArticulo, System.DateTime FechaInicio, System.DateTime FechaFin, int Opcion) {
            return base.Channel.ObtenerInventarioEnProceso(CodAlmacen, CodPlanta, CodProceso, CodTipoArticulo, CodArticulo, FechaInicio, FechaFin, Opcion);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerInventario(int CodPlanta, System.DateTime FechaInicio, System.DateTime FechaFin) {
            return base.Channel.ObtenerInventario(CodPlanta, FechaInicio, FechaFin);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerPiezasReemplazo(bool SinPiezasreemplazadas) {
            return base.Channel.ObtenerPiezasReemplazo(SinPiezasreemplazadas);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerConfig(int CodConfiguracion) {
            return base.Channel.ObtenerConfig(CodConfiguracion);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerRepCapInstalada(int Opcion, int Planta, int CT, int Banco, int TipoArt, int Molde) {
            return base.Channel.ObtenerRepCapInstalada(Opcion, Planta, CT, Banco, TipoArt, Molde);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerMetasProd(int CodPlanta, System.DateTime FechaInicio, System.DateTime FechaFin) {
            return base.Channel.ObtenerMetasProd(CodPlanta, FechaInicio, FechaFin);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerKardexProductoBusqueda(string Codigo) {
            return base.Channel.ObtenerKardexProductoBusqueda(Codigo);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerKardexProducto(int Codigo) {
            return base.Channel.ObtenerKardexProducto(Codigo);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerKardexProductoDefecto(int Codigo) {
            return base.Channel.ObtenerKardexProductoDefecto(Codigo);
        }
        
        public void GuardarPlanta(LAMOSA.SCPP.Server.BusinessEntity.Planta Planta) {
            base.Channel.GuardarPlanta(Planta);
        }
        
        public void GuardarPrueba(LAMOSA.SCPP.Server.BusinessEntity.Prueba Prueba, int iCodPlanta) {
            base.Channel.GuardarPrueba(Prueba, iCodPlanta);
        }
        
        public LAMOSA.SCPP.Server.BusinessEntity.Usuario GuardarUsuario(LAMOSA.SCPP.Server.BusinessEntity.Usuario Usuario) {
            return base.Channel.GuardarUsuario(Usuario);
        }
        
        public void GuardarTurno(LAMOSA.SCPP.Server.BusinessEntity.Turno Turno) {
            base.Channel.GuardarTurno(Turno);
        }
        
        public void GuardarCondicionPasta(LAMOSA.SCPP.Server.BusinessEntity.CondicionPasta CP) {
            base.Channel.GuardarCondicionPasta(CP);
        }
        
        public void GuardarCondicionOperacion(LAMOSA.SCPP.Server.BusinessEntity.CondicionOperacionGuarda CO) {
            base.Channel.GuardarCondicionOperacion(CO);
        }
        
        public void GuardaRol(LAMOSA.SCPP.Server.BusinessEntity.rolplanta RolPlanta) {
            base.Channel.GuardaRol(RolPlanta);
        }
        
        public void GuardarConfig(LAMOSA.SCPP.Server.BusinessEntity.Configuracion Conf) {
            base.Channel.GuardarConfig(Conf);
        }
        
        public void GuardarCondicionEsmalte(LAMOSA.SCPP.Server.BusinessEntity.CondicionEsmalte CE) {
            base.Channel.GuardarCondicionEsmalte(CE);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerTurnos() {
            return base.Channel.ObtenerTurnos();
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerCalidades() {
            return base.Channel.ObtenerCalidades();
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerCalidadesCbo() {
            return base.Channel.ObtenerCalidadesCbo();
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerPlantaCalidadCbo(int CodPlanta) {
            return base.Channel.ObtenerPlantaCalidadCbo(CodPlanta);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerDefectosCbo(int CodProceso, int CodTipoDefecto) {
            return base.Channel.ObtenerDefectosCbo(CodProceso, CodTipoDefecto);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerZonaDefectoCbo() {
            return base.Channel.ObtenerZonaDefectoCbo();
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerColores() {
            return base.Channel.ObtenerColores();
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerArticulos(LAMOSA.SCPP.Server.BusinessEntity.ArticuloPars articuloPars) {
            return base.Channel.ObtenerArticulos(articuloPars);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerArticulosCbo(int tipoArticulo) {
            return base.Channel.ObtenerArticulosCbo(tipoArticulo);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerModelosCbo(int tipoArticulo) {
            return base.Channel.ObtenerModelosCbo(tipoArticulo);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerTiposArticuloCbo() {
            return base.Channel.ObtenerTiposArticuloCbo();
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerMoldesCbo(LAMOSA.SCPP.Server.BusinessEntity.ArticuloPars articuloPars) {
            return base.Channel.ObtenerMoldesCbo(articuloPars);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerMoldes(LAMOSA.SCPP.Server.BusinessEntity.ArticuloPars articuloPars) {
            return base.Channel.ObtenerMoldes(articuloPars);
        }
        
        public LAMOSA.SCPP.Server.BusinessEntity.LoginUsuario Login(LAMOSA.SCPP.Server.BusinessEntity.LoginUsuario lu) {
            return base.Channel.Login(lu);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerPruebas(int Proceso) {
            return base.Channel.ObtenerPruebas(Proceso);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerDefectos(int CodProceso, int CodPlanta) {
            return base.Channel.ObtenerDefectos(CodProceso, CodPlanta);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerTiposDefecto() {
            return base.Channel.ObtenerTiposDefecto();
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerZonaDefecto(int CodTipoArticulo) {
            return base.Channel.ObtenerZonaDefecto(CodTipoArticulo);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerAlmacen() {
            return base.Channel.ObtenerAlmacen();
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerAlmacenCbo() {
            return base.Channel.ObtenerAlmacenCbo();
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerPlanta(int Almacen) {
            return base.Channel.ObtenerPlanta(Almacen);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerCentroTrabajo(int Planta, int Proceso) {
            return base.Channel.ObtenerCentroTrabajo(Planta, Proceso);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerCentroTrabajoCbo(int Planta, int Proceso) {
            return base.Channel.ObtenerCentroTrabajoCbo(Planta, Proceso);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerArea(int CT) {
            return base.Channel.ObtenerArea(CT);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerEstructuraPlanta(int Planta) {
            return base.Channel.ObtenerEstructuraPlanta(Planta);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerProcesoCbo(int Planta) {
            return base.Channel.ObtenerProcesoCbo(Planta);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerProceso() {
            return base.Channel.ObtenerProceso();
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerRutaProceso(int Planta) {
            return base.Channel.ObtenerRutaProceso(Planta);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerRol() {
            return base.Channel.ObtenerRol();
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerRolCbo() {
            return base.Channel.ObtenerRolCbo();
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerEmpleado(int CodPlanta, int CodPuesto) {
            return base.Channel.ObtenerEmpleado(CodPlanta, CodPuesto);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerPlantaCbo() {
            return base.Channel.ObtenerPlantaCbo();
        }
    }
}
