//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAMOSA.SCPP.Client.View.Administrador.svcSCPPHH {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svcSCPPHH.ISCPP_HH")]
    public interface ISCPP_HH {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerModeloTipoPieza", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerModeloTipoPiezaResponse")]
        System.Data.DataTable ObtenerModeloTipoPieza(int articulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerModeloTipoPieza2", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerModeloTipoPieza2Response")]
        System.Data.DataTable ObtenerModeloTipoPieza2(int iCodPieza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerColorPieza", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerColorPiezaResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerColorPieza(int iCodPieza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ValidarPieza", ReplyAction="http://tempuri.org/ISCPP_HH/ValidarPiezaResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ValidarPieza(string sCodBarras, int iCodProcesoAct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ValidarTarimaPieza", ReplyAction="http://tempuri.org/ISCPP_HH/ValidarTarimaPiezaResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ValidarTarimaPieza(int iTarima, int sCodPieza, int sCodPiezaPadre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/DeleteTarimaPieza", ReplyAction="http://tempuri.org/ISCPP_HH/DeleteTarimaPiezaResponse")]
        int DeleteTarimaPieza(int iTarima, int iPieza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/EsCasetaTanque", ReplyAction="http://tempuri.org/ISCPP_HH/EsCasetaTanqueResponse")]
        bool EsCasetaTanque(int iCodCaseta, int iCodTanque, int iCodProceso, int iCodPlanta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ImprimirEtiqueta", ReplyAction="http://tempuri.org/ISCPP_HH/ImprimirEtiquetaResponse")]
        void ImprimirEtiqueta(LAMOSA.SCPP.Server.BusinessEntity.ConfigImpresora cConfigImpresora, LAMOSA.SCPP.Server.BusinessEntity.Etiqueta eEtiqueta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerPieza", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerPiezaResponse")]
        System.Data.DataTable ObtenerPieza(int iCodPieza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerPiezasRequeme", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerPiezasRequemeResponse")]
        System.Data.DataTable ObtenerPiezasRequeme(int iCodPlanta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ProcesarBatchEsmaltadoPiezas", ReplyAction="http://tempuri.org/ISCPP_HH/ProcesarBatchEsmaltadoPiezasResponse")]
        System.Data.DataSet ProcesarBatchEsmaltadoPiezas(System.Data.DataSet dsParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ProcesarBatchVaciadoPieza", ReplyAction="http://tempuri.org/ISCPP_HH/ProcesarBatchVaciadoPiezaResponse")]
        System.Data.DataSet ProcesarBatchVaciadoPieza(System.Data.DataTable dtPieza, System.Data.DataTable dtPiezaTransaccion, System.Data.DataTable dtVaciadas, System.Data.DataTable dtCarroPieza, System.Data.DataTable dtPiezaDefecto, System.Data.DataTable dtEstadoPieza, System.Data.DataTable dtProcesoPieza, System.Data.DataTable dtPuebaProceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ProcesarBatchSecadoPieza", ReplyAction="http://tempuri.org/ISCPP_HH/ProcesarBatchSecadoPiezaResponse")]
        System.Data.DataSet ProcesarBatchSecadoPieza(System.Data.DataTable dtPieza, System.Data.DataTable dtPiezaTransaccion, System.Data.DataTable dtPiezaTransaccionSecador, System.Data.DataTable dtCarroPieza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerFechaServidor", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerFechaServidorResponse")]
        System.DateTime ObtenerFechaServidor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ProcesarBatchRevisadoPieza", ReplyAction="http://tempuri.org/ISCPP_HH/ProcesarBatchRevisadoPiezaResponse")]
        System.Data.DataSet ProcesarBatchRevisadoPieza(System.Data.DataSet dsRevisado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ProcesarBatchHornosPieza", ReplyAction="http://tempuri.org/ISCPP_HH/ProcesarBatchHornosPiezaResponse")]
        System.Data.DataSet ProcesarBatchHornosPieza(System.Data.DataSet dsHornos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerConfigBancoCasetaTanque", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerConfigBancoCasetaTanqueResponse")]
        int ObtenerConfigBancoCasetaTanque(int iCodMaquina, int iCodTanque, int iCodProceso, int iCodPlanta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerOperador", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerOperadorResponse")]
        System.Data.DataTable ObtenerOperador(int iOperador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/LogIns", ReplyAction="http://tempuri.org/ISCPP_HH/LogInsResponse")]
        System.Data.DataSet LogIns(System.Data.DataSet dsLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerTipoArticuloPieza", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerTipoArticuloPiezaResponse")]
        System.Data.DataTable ObtenerTipoArticuloPieza(int iCodigoPieza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerKardexPieza", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerKardexPiezaResponse")]
        System.Data.DataSet ObtenerKardexPieza(System.Nullable<int> iCodigoPieza, string sCodigoBarras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerCarrosPendientesSecador", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerCarrosPendientesSecadorResponse")]
        System.Data.DataTable ObtenerCarrosPendientesSecador(int iCodigoPlanta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerCarrosPendientesSecadorDetalle", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerCarrosPendientesSecadorDetalleResponse")]
        System.Data.DataTable ObtenerCarrosPendientesSecadorDetalle(int iCarro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerProduccion", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerProduccionResponse")]
        System.Data.DataTable ObtenerProduccion(int iCodigoOperador, int iCodigoProceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerMensajeInicioSesion", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerMensajeInicioSesionResponse")]
        string ObtenerMensajeInicioSesion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ValidarPoliticaContrasena", ReplyAction="http://tempuri.org/ISCPP_HH/ValidarPoliticaContrasenaResponse")]
        bool ValidarPoliticaContrasena(string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/HHSyncCarroPiezaQuemadoIns", ReplyAction="http://tempuri.org/ISCPP_HH/HHSyncCarroPiezaQuemadoInsResponse")]
        int HHSyncCarroPiezaQuemadoIns(int codPlanta, int codPieza, int codCarro, int codZona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/HHSyncConfigHandHeldIns", ReplyAction="http://tempuri.org/ISCPP_HH/HHSyncConfigHandHeldInsResponse")]
        int HHSyncConfigHandHeldIns(int codTurno, int codUsuario, int codSupervisor, int codOperador, int codConfigBanco, int codProceso, int codPlanta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/HHSyncPiezaIns", ReplyAction="http://tempuri.org/ISCPP_HH/HHSyncPiezaInsResponse")]
        int HHSyncPiezaIns(int codBarras, int codConfigBanco, int codConsecutivo, int posicion, int codArticulo, int codColor, int codCalidad, int codPlanta, int codUltimoEstado, int codUltimoProceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/HHSyncPiezaReemplazoIns", ReplyAction="http://tempuri.org/ISCPP_HH/HHSyncPiezaReemplazoInsResponse")]
        int HHSyncPiezaReemplazoIns(int codPieza, int codProceso, int codPiezaAnterior);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/HHSyncPiezaDefectoIns", ReplyAction="http://tempuri.org/ISCPP_HH/HHSyncPiezaDefectoInsResponse")]
        int HHSyncPiezaDefectoIns(int codPieza, int codProceso, int codDefecto, int codZonaDefecto, int codEstadoDefecto, int codPiezaDefectoDet, int codPiezaDefectoDetalle, int codEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/HHSyncPiezaTransaccionIns", ReplyAction="http://tempuri.org/ISCPP_HH/HHSyncPiezaTransaccionInsResponse")]
        int HHSyncPiezaTransaccionIns(int codConfigHH, int CodPieza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/HHSyncPiezaTransaccionSecadorIns", ReplyAction="http://tempuri.org/ISCPP_HH/HHSyncPiezaTransaccionSecadorInsResponse")]
        int HHSyncPiezaTransaccionSecadorIns(int codPiezaTranzaccion, System.DateTime horaInicio, float horasSecado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/BloquearUsuario", ReplyAction="http://tempuri.org/ISCPP_HH/BloquearUsuarioResponse")]
        int BloquearUsuario(int codUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/IncrementarContadorIntentos", ReplyAction="http://tempuri.org/ISCPP_HH/IncrementarContadorIntentosResponse")]
        int IncrementarContadorIntentos(int codUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ReiniciarContadorIntentos", ReplyAction="http://tempuri.org/ISCPP_HH/ReiniciarContadorIntentosResponse")]
        int ReiniciarContadorIntentos(int codUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/InsertarTarima", ReplyAction="http://tempuri.org/ISCPP_HH/InsertarTarimaResponse")]
        int InsertarTarima(int codTarima, int codPieza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerPiezaInventario", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerPiezaInventarioResponse")]
        int ObtenerPiezaInventario(int codPieza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ActualizarPiezaInventario", ReplyAction="http://tempuri.org/ISCPP_HH/ActualizarPiezaInventarioResponse")]
        int ActualizarPiezaInventario(int codPieza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/InsertarPiezaInventario", ReplyAction="http://tempuri.org/ISCPP_HH/InsertarPiezaInventarioResponse")]
        int InsertarPiezaInventario(string barras, int planta, int proceso, int configBanco, int consecutivo, int posicion, int articulo, int color, int calidad, int ultimoEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/InsertaPiezaReemplazo", ReplyAction="http://tempuri.org/ISCPP_HH/InsertaPiezaReemplazoResponse")]
        int InsertaPiezaReemplazo(int codPieza, int codProceso, int codPiezaAnterior);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ExisteCambioEnProceso", ReplyAction="http://tempuri.org/ISCPP_HH/ExisteCambioEnProcesoResponse")]
        bool ExisteCambioEnProceso(int proceso, int pantalla, System.DateTime fechaUltActualizacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/EnvioDT", ReplyAction="http://tempuri.org/ISCPP_HH/EnvioDTResponse")]
        System.Data.DataSet EnvioDT(System.Data.DataSet dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/InsertaError", ReplyAction="http://tempuri.org/ISCPP_HH/InsertaErrorResponse")]
        void InsertaError(string parameters, string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerModelos2", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerModelos2Response")]
        System.Data.DataTable ObtenerModelos2(int molde);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ActualizarModeloPieza", ReplyAction="http://tempuri.org/ISCPP_HH/ActualizarModeloPiezaResponse")]
        int ActualizarModeloPieza(int pieza, int modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ActualizarCalidadPieza", ReplyAction="http://tempuri.org/ISCPP_HH/ActualizarCalidadPiezaResponse")]
        int ActualizarCalidadPieza(int pieza, int calidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerDefectos", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerDefectosResponse")]
        System.Data.DataTable ObtenerDefectos(int iProceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerZonasDefecto", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerZonasDefectoResponse")]
        System.Data.DataTable ObtenerZonasDefecto(int iTipoArticulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerEstadosDefecto", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerEstadosDefectoResponse")]
        System.Data.DataTable ObtenerEstadosDefecto(int estadoDefecto1, int estadoDefecto2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerCalidades", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerCalidadesResponse")]
        System.Data.DataTable ObtenerCalidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ExisteModelo", ReplyAction="http://tempuri.org/ISCPP_HH/ExisteModeloResponse")]
        int ExisteModelo(string claveArticulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerDesProceso", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerDesProcesoResponse")]
        string ObtenerDesProceso(int proceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerTiposModelo", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerTiposModeloResponse")]
        System.Data.DataTable ObtenerTiposModelo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerModelos", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerModelosResponse")]
        System.Data.DataTable ObtenerModelos(int tipoModelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ExisteModeloHastaRevisado", ReplyAction="http://tempuri.org/ISCPP_HH/ExisteModeloHastaRevisadoResponse")]
        int ExisteModeloHastaRevisado(string claveArticulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ExisteModeloDesdeEsmaltado", ReplyAction="http://tempuri.org/ISCPP_HH/ExisteModeloDesdeEsmaltadoResponse")]
        int ExisteModeloDesdeEsmaltado(string claveArticulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/EstaEnInventarioPocesoPieza", ReplyAction="http://tempuri.org/ISCPP_HH/EstaEnInventarioPocesoPiezaResponse")]
        int EstaEnInventarioPocesoPieza(string claveArticulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerCodMoldePieza", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerCodMoldePiezaResponse")]
        int ObtenerCodMoldePieza(int iCodPieza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerDefectosPiezaProceso", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerDefectosPiezaProcesoResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerDefectosPiezaProceso(int iCodPieza, int iCodProceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/InsertarPieza", ReplyAction="http://tempuri.org/ISCPP_HH/InsertarPiezaResponse")]
        int InsertarPieza(int iCodPlanta, string sCodBarras, int iCodConfigBanco, int iCodConsecutivo, int iPosicion, int iCodArticulo, int iCodUltimoProceso, int iCodUltimoEstado, System.DateTime fechaRegistro, int iMolde, int iBase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/InsertarPiezaTransaccion", ReplyAction="http://tempuri.org/ISCPP_HH/InsertarPiezaTransaccionResponse")]
        long InsertarPiezaTransaccion(long lCodConfigHandheld, int iCodPieza, System.DateTime dtFechaRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ActulizarUltimoProcesoPieza", ReplyAction="http://tempuri.org/ISCPP_HH/ActulizarUltimoProcesoPiezaResponse")]
        int ActulizarUltimoProcesoPieza(int iCodPieza, int iCodUltimoProceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/EliminarCarro", ReplyAction="http://tempuri.org/ISCPP_HH/EliminarCarroResponse")]
        int EliminarCarro(int iCodPlanta, int iCodProceso, int iCodCarro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ActualizarConfigHandHeld", ReplyAction="http://tempuri.org/ISCPP_HH/ActualizarConfigHandHeldResponse")]
        int ActualizarConfigHandHeld(long lCodConfigHandHeld, int iCodSupervisor, int iCodOperador, int iCodConfigBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/InsertarCarroPieza", ReplyAction="http://tempuri.org/ISCPP_HH/InsertarCarroPiezaResponse")]
        int InsertarCarroPieza(int iCodPlanta, int iCodProceso, int iCodCarro, int iCodPieza, System.DateTime dFechaRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/InsertarPiezaTransaccionSecador", ReplyAction="http://tempuri.org/ISCPP_HH/InsertarPiezaTransaccionSecadorResponse")]
        int InsertarPiezaTransaccionSecador(long lCodPiezaTransaccion, System.DateTime dtHoraInicio, double dHorasSecado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ActualizarColorPieza", ReplyAction="http://tempuri.org/ISCPP_HH/ActualizarColorPiezaResponse")]
        int ActualizarColorPieza(int iCodPieza, int iCodColor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/InsertarCarroZonaPieza", ReplyAction="http://tempuri.org/ISCPP_HH/InsertarCarroZonaPiezaResponse")]
        int InsertarCarroZonaPieza(int iCodPlanta, int iCodPieza, int iCodCarro, string sCodZona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/InsertarPiezaDefecto", ReplyAction="http://tempuri.org/ISCPP_HH/InsertarPiezaDefectoResponse")]
        int InsertarPiezaDefecto(int iCodPieza, int iCodProceso, int iCodDefecto, int iCodZonaDefecto, int iCodEstadoDefecto, int iCodEmpleado, System.DateTime dtFechaUltimoMovimiento, System.DateTime dtFechaRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/EliminarPiezaDefecto", ReplyAction="http://tempuri.org/ISCPP_HH/EliminarPiezaDefectoResponse")]
        int EliminarPiezaDefecto(int iCodPieza, int iCodProceso, int iCodDefecto, int iCodZonaDefecto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ActualizarPiezaDefecto", ReplyAction="http://tempuri.org/ISCPP_HH/ActualizarPiezaDefectoResponse")]
        int ActualizarPiezaDefecto(int iCodPieza, int iCodProceso, int iCodDefecto, int iCodZonaDefecto, int iCodEstadoDefecto, int iCodEmpleado, System.DateTime dtFechaUltimoMovimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ActualizarPiezaUltimoEstado", ReplyAction="http://tempuri.org/ISCPP_HH/ActualizarPiezaUltimoEstadoResponse")]
        int ActualizarPiezaUltimoEstado(int iCodPieza, int iCodUltimoEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ActualizarPiezaAuditada", ReplyAction="http://tempuri.org/ISCPP_HH/ActualizarPiezaAuditadaResponse")]
        int ActualizarPiezaAuditada(int iCodPieza, bool bAuditada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerPiezasTarima", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerPiezasTarimaResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerPiezasTarima(int iCodTarima);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/RechazarTarimaPieza", ReplyAction="http://tempuri.org/ISCPP_HH/RechazarTarimaPiezaResponse")]
        int RechazarTarimaPieza(int iCodTarima);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ActualizarTarimaPaletizado", ReplyAction="http://tempuri.org/ISCPP_HH/ActualizarTarimaPaletizadoResponse")]
        int ActualizarTarimaPaletizado(int iCodTarima, bool bPaletizado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ExistePiezaEnTarima", ReplyAction="http://tempuri.org/ISCPP_HH/ExistePiezaEnTarimaResponse")]
        int ExistePiezaEnTarima(int iPieza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/InsertarTarimaPieza", ReplyAction="http://tempuri.org/ISCPP_HH/InsertarTarimaPiezaResponse")]
        int InsertarTarimaPieza(int iTarima, int iPieza, bool iPaletizado, bool iRechazado, System.DateTime FechaRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/InsertarEtiquetaReemplazo", ReplyAction="http://tempuri.org/ISCPP_HH/InsertarEtiquetaReemplazoResponse")]
        int InsertarEtiquetaReemplazo(int iCodPlanta, string sCodBarras, int iCodModelo, int iCodColor, int iCodCalidad, int iCodUltimoProceso, int iCodUltimoEstado, long lCodConfigHandheld, System.DateTime dtFechaRegistro, int iCodProcesoPiezaReem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerFechaDepuracionHistoria", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerFechaDepuracionHistoriaResponse")]
        System.DateTime ObtenerFechaDepuracionHistoria();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerFechaDepuracionHistoria2", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerFechaDepuracionHistoria2Response")]
        System.DateTime ObtenerFechaDepuracionHistoria2(int iCodigoPlanta, int iCodigoProceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/SyncServHH", ReplyAction="http://tempuri.org/ISCPP_HH/SyncServHHResponse")]
        System.Data.DataSet SyncServHH(string NombreSPTabla, System.DateTime fechaIns, System.DateTime fechaUpd, System.DateTime fechaDel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ActualizarCatalogos", ReplyAction="http://tempuri.org/ISCPP_HH/ActualizarCatalogosResponse")]
        System.Data.DataSet ActualizarCatalogos(string tabla, int planta, int proceso, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ActualizarCatalogosPorPiezas", ReplyAction="http://tempuri.org/ISCPP_HH/ActualizarCatalogosPorPiezasResponse")]
        System.Data.DataSet ActualizarCatalogosPorPiezas(System.Data.DataTable piezas, string tabla, int proceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ActualizarTransacciones", ReplyAction="http://tempuri.org/ISCPP_HH/ActualizarTransaccionesResponse")]
        System.Data.DataSet ActualizarTransacciones(string tabla, int planta, int proceso, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/SyncServHHLDS", ReplyAction="http://tempuri.org/ISCPP_HH/SyncServHHLDSResponse")]
        System.Collections.Generic.List<System.Data.DataSet> SyncServHHLDS(System.DateTime fechaIns, System.DateTime fechaUpd, System.DateTime fechaDel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/TablasCatalogosHH", ReplyAction="http://tempuri.org/ISCPP_HH/TablasCatalogosHHResponse")]
        System.Data.DataTable TablasCatalogosHH();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/TablasProcesoHH", ReplyAction="http://tempuri.org/ISCPP_HH/TablasProcesoHHResponse")]
        System.Data.DataTable TablasProcesoHH(int planta, int proceso, int pantalla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/HHSyncCarroPiezaIns", ReplyAction="http://tempuri.org/ISCPP_HH/HHSyncCarroPiezaInsResponse")]
        int HHSyncCarroPiezaIns(int codPlanta, int codProceso, int codCarro, int codPieza, int codZona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/EstaServicioDisponible", ReplyAction="http://tempuri.org/ISCPP_HH/EstaServicioDisponibleResponse")]
        bool EstaServicioDisponible();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerPlantas", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerPlantasResponse")]
        System.Data.DataTable ObtenerPlantas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerProcesos", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerProcesosResponse")]
        System.Data.DataTable ObtenerProcesos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/Login", ReplyAction="http://tempuri.org/ISCPP_HH/LoginResponse")]
        System.Data.DataTable Login(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerPlantasRol", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerPlantasRolResponse")]
        System.Data.DataTable ObtenerPlantasRol(int iCodRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerProcesosPorRol", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerProcesosPorRolResponse")]
        System.Data.DataTable ObtenerProcesosPorRol(int Rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerTurnos", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerTurnosResponse")]
        System.Data.DataTable ObtenerTurnos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerProcesos2", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerProcesos2Response")]
        System.Data.DataTable ObtenerProcesos2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerPantallasProceso", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerPantallasProcesoResponse")]
        System.Data.DataTable ObtenerPantallasProceso(int iCodProceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/InsertarConfigHandHeld", ReplyAction="http://tempuri.org/ISCPP_HH/InsertarConfigHandHeldResponse")]
        long InsertarConfigHandHeld(int iCodUsuario, int iCodOperador, int iCodSupervisor, System.DateTime dtFecha, int iCodTurno, int iCodPlanta, int iCodProceso, int iCodConfigBanco, System.DateTime dtFechaRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ExisteInventarioProcesoActivo", ReplyAction="http://tempuri.org/ISCPP_HH/ExisteInventarioProcesoActivoResponse")]
        int ExisteInventarioProcesoActivo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerClaveEmpleadoMFG", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerClaveEmpleadoMFGResponse")]
        int ObtenerClaveEmpleadoMFG(int empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerSupervisorPorDefecto", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerSupervisorPorDefectoResponse")]
        System.Data.DataTable ObtenerSupervisorPorDefecto(int empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ValidarEmpleadoMFG", ReplyAction="http://tempuri.org/ISCPP_HH/ValidarEmpleadoMFGResponse")]
        int ValidarEmpleadoMFG(int empleadoMFG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerCentrosTrabajo", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerCentrosTrabajoResponse")]
        System.Data.DataTable ObtenerCentrosTrabajo(int planta, int proceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerMaquinas", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerMaquinasResponse")]
        System.Data.DataTable ObtenerMaquinas(int planta, int proceso, int centroTrabajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerPosicionesBanco", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerPosicionesBancoResponse")]
        System.Data.DataTable ObtenerPosicionesBanco(int configBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerArticulosMolde", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerArticulosMoldeResponse")]
        System.Data.DataTable ObtenerArticulosMolde(int molde);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerColores", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerColoresResponse")]
        System.Data.DataTable ObtenerColores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerPruebas", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerPruebasResponse")]
        System.Data.DataTable ObtenerPruebas(int planta, int proceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerPiezaCarroHornos", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerPiezaCarroHornosResponse")]
        System.Data.DataTable ObtenerPiezaCarroHornos(int planta, int carro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ActualizarVaciadasAcumuladas", ReplyAction="http://tempuri.org/ISCPP_HH/ActualizarVaciadasAcumuladasResponse")]
        int ActualizarVaciadasAcumuladas(int iCodConfigBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerNumPosicionesBanco", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerNumPosicionesBancoResponse")]
        int ObtenerNumPosicionesBanco(int configBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/SuperoLimiteVaciadas", ReplyAction="http://tempuri.org/ISCPP_HH/SuperoLimiteVaciadasResponse")]
        bool SuperoLimiteVaciadas(int configBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ActualizarVaciadasAcumuladas2", ReplyAction="http://tempuri.org/ISCPP_HH/ActualizarVaciadasAcumuladas2Response")]
        int ActualizarVaciadasAcumuladas2(int iCodConfigBanco, int cant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerCodPiezaCodBarras", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerCodPiezaCodBarrasResponse")]
        int ObtenerCodPiezaCodBarras(string sCodBarras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerEstadoPieza", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerEstadoPiezaResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerEstadoPieza(int iCodPieza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerUltimoProcesoPieza", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerUltimoProcesoPiezaResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerUltimoProcesoPieza(int iCodPieza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerPiezasCarro", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerPiezasCarroResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerPiezasCarro(int iCodPlanta, int iCodProceso, int iCodCarro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerCodModeloPieza", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerCodModeloPiezaResponse")]
        int ObtenerCodModeloPieza(int iCodPieza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ExistePiezaEnCarro", ReplyAction="http://tempuri.org/ISCPP_HH/ExistePiezaEnCarroResponse")]
        int ExistePiezaEnCarro(int iCodPlanta, int iCodProceso, int iCodPieza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCPP_HH/ObtenerCalidadPieza", ReplyAction="http://tempuri.org/ISCPP_HH/ObtenerCalidadPiezaResponse")]
        System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerCalidadPieza(int iCodPieza);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISCPP_HHChannel : LAMOSA.SCPP.Client.View.Administrador.svcSCPPHH.ISCPP_HH, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SCPP_HHClient : System.ServiceModel.ClientBase<LAMOSA.SCPP.Client.View.Administrador.svcSCPPHH.ISCPP_HH>, LAMOSA.SCPP.Client.View.Administrador.svcSCPPHH.ISCPP_HH {
        
        public SCPP_HHClient() {
        }
        
        public SCPP_HHClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SCPP_HHClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCPP_HHClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCPP_HHClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ObtenerModeloTipoPieza(int articulo) {
            return base.Channel.ObtenerModeloTipoPieza(articulo);
        }
        
        public System.Data.DataTable ObtenerModeloTipoPieza2(int iCodPieza) {
            return base.Channel.ObtenerModeloTipoPieza2(iCodPieza);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerColorPieza(int iCodPieza) {
            return base.Channel.ObtenerColorPieza(iCodPieza);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ValidarPieza(string sCodBarras, int iCodProcesoAct) {
            return base.Channel.ValidarPieza(sCodBarras, iCodProcesoAct);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ValidarTarimaPieza(int iTarima, int sCodPieza, int sCodPiezaPadre) {
            return base.Channel.ValidarTarimaPieza(iTarima, sCodPieza, sCodPiezaPadre);
        }
        
        public int DeleteTarimaPieza(int iTarima, int iPieza) {
            return base.Channel.DeleteTarimaPieza(iTarima, iPieza);
        }
        
        public bool EsCasetaTanque(int iCodCaseta, int iCodTanque, int iCodProceso, int iCodPlanta) {
            return base.Channel.EsCasetaTanque(iCodCaseta, iCodTanque, iCodProceso, iCodPlanta);
        }
        
        public void ImprimirEtiqueta(LAMOSA.SCPP.Server.BusinessEntity.ConfigImpresora cConfigImpresora, LAMOSA.SCPP.Server.BusinessEntity.Etiqueta eEtiqueta) {
            base.Channel.ImprimirEtiqueta(cConfigImpresora, eEtiqueta);
        }
        
        public System.Data.DataTable ObtenerPieza(int iCodPieza) {
            return base.Channel.ObtenerPieza(iCodPieza);
        }
        
        public System.Data.DataTable ObtenerPiezasRequeme(int iCodPlanta) {
            return base.Channel.ObtenerPiezasRequeme(iCodPlanta);
        }
        
        public System.Data.DataSet ProcesarBatchEsmaltadoPiezas(System.Data.DataSet dsParameters) {
            return base.Channel.ProcesarBatchEsmaltadoPiezas(dsParameters);
        }
        
        public System.Data.DataSet ProcesarBatchVaciadoPieza(System.Data.DataTable dtPieza, System.Data.DataTable dtPiezaTransaccion, System.Data.DataTable dtVaciadas, System.Data.DataTable dtCarroPieza, System.Data.DataTable dtPiezaDefecto, System.Data.DataTable dtEstadoPieza, System.Data.DataTable dtProcesoPieza, System.Data.DataTable dtPuebaProceso) {
            return base.Channel.ProcesarBatchVaciadoPieza(dtPieza, dtPiezaTransaccion, dtVaciadas, dtCarroPieza, dtPiezaDefecto, dtEstadoPieza, dtProcesoPieza, dtPuebaProceso);
        }
        
        public System.Data.DataSet ProcesarBatchSecadoPieza(System.Data.DataTable dtPieza, System.Data.DataTable dtPiezaTransaccion, System.Data.DataTable dtPiezaTransaccionSecador, System.Data.DataTable dtCarroPieza) {
            return base.Channel.ProcesarBatchSecadoPieza(dtPieza, dtPiezaTransaccion, dtPiezaTransaccionSecador, dtCarroPieza);
        }
        
        public System.DateTime ObtenerFechaServidor() {
            return base.Channel.ObtenerFechaServidor();
        }
        
        public System.Data.DataSet ProcesarBatchRevisadoPieza(System.Data.DataSet dsRevisado) {
            return base.Channel.ProcesarBatchRevisadoPieza(dsRevisado);
        }
        
        public System.Data.DataSet ProcesarBatchHornosPieza(System.Data.DataSet dsHornos) {
            return base.Channel.ProcesarBatchHornosPieza(dsHornos);
        }
        
        public int ObtenerConfigBancoCasetaTanque(int iCodMaquina, int iCodTanque, int iCodProceso, int iCodPlanta) {
            return base.Channel.ObtenerConfigBancoCasetaTanque(iCodMaquina, iCodTanque, iCodProceso, iCodPlanta);
        }
        
        public System.Data.DataTable ObtenerOperador(int iOperador) {
            return base.Channel.ObtenerOperador(iOperador);
        }
        
        public System.Data.DataSet LogIns(System.Data.DataSet dsLog) {
            return base.Channel.LogIns(dsLog);
        }
        
        public System.Data.DataTable ObtenerTipoArticuloPieza(int iCodigoPieza) {
            return base.Channel.ObtenerTipoArticuloPieza(iCodigoPieza);
        }
        
        public System.Data.DataSet ObtenerKardexPieza(System.Nullable<int> iCodigoPieza, string sCodigoBarras) {
            return base.Channel.ObtenerKardexPieza(iCodigoPieza, sCodigoBarras);
        }
        
        public System.Data.DataTable ObtenerCarrosPendientesSecador(int iCodigoPlanta) {
            return base.Channel.ObtenerCarrosPendientesSecador(iCodigoPlanta);
        }
        
        public System.Data.DataTable ObtenerCarrosPendientesSecadorDetalle(int iCarro) {
            return base.Channel.ObtenerCarrosPendientesSecadorDetalle(iCarro);
        }
        
        public System.Data.DataTable ObtenerProduccion(int iCodigoOperador, int iCodigoProceso) {
            return base.Channel.ObtenerProduccion(iCodigoOperador, iCodigoProceso);
        }
        
        public string ObtenerMensajeInicioSesion() {
            return base.Channel.ObtenerMensajeInicioSesion();
        }
        
        public bool ValidarPoliticaContrasena(string contrasena) {
            return base.Channel.ValidarPoliticaContrasena(contrasena);
        }
        
        public int HHSyncCarroPiezaQuemadoIns(int codPlanta, int codPieza, int codCarro, int codZona) {
            return base.Channel.HHSyncCarroPiezaQuemadoIns(codPlanta, codPieza, codCarro, codZona);
        }
        
        public int HHSyncConfigHandHeldIns(int codTurno, int codUsuario, int codSupervisor, int codOperador, int codConfigBanco, int codProceso, int codPlanta) {
            return base.Channel.HHSyncConfigHandHeldIns(codTurno, codUsuario, codSupervisor, codOperador, codConfigBanco, codProceso, codPlanta);
        }
        
        public int HHSyncPiezaIns(int codBarras, int codConfigBanco, int codConsecutivo, int posicion, int codArticulo, int codColor, int codCalidad, int codPlanta, int codUltimoEstado, int codUltimoProceso) {
            return base.Channel.HHSyncPiezaIns(codBarras, codConfigBanco, codConsecutivo, posicion, codArticulo, codColor, codCalidad, codPlanta, codUltimoEstado, codUltimoProceso);
        }
        
        public int HHSyncPiezaReemplazoIns(int codPieza, int codProceso, int codPiezaAnterior) {
            return base.Channel.HHSyncPiezaReemplazoIns(codPieza, codProceso, codPiezaAnterior);
        }
        
        public int HHSyncPiezaDefectoIns(int codPieza, int codProceso, int codDefecto, int codZonaDefecto, int codEstadoDefecto, int codPiezaDefectoDet, int codPiezaDefectoDetalle, int codEmpleado) {
            return base.Channel.HHSyncPiezaDefectoIns(codPieza, codProceso, codDefecto, codZonaDefecto, codEstadoDefecto, codPiezaDefectoDet, codPiezaDefectoDetalle, codEmpleado);
        }
        
        public int HHSyncPiezaTransaccionIns(int codConfigHH, int CodPieza) {
            return base.Channel.HHSyncPiezaTransaccionIns(codConfigHH, CodPieza);
        }
        
        public int HHSyncPiezaTransaccionSecadorIns(int codPiezaTranzaccion, System.DateTime horaInicio, float horasSecado) {
            return base.Channel.HHSyncPiezaTransaccionSecadorIns(codPiezaTranzaccion, horaInicio, horasSecado);
        }
        
        public int BloquearUsuario(int codUsuario) {
            return base.Channel.BloquearUsuario(codUsuario);
        }
        
        public int IncrementarContadorIntentos(int codUsuario) {
            return base.Channel.IncrementarContadorIntentos(codUsuario);
        }
        
        public int ReiniciarContadorIntentos(int codUsuario) {
            return base.Channel.ReiniciarContadorIntentos(codUsuario);
        }
        
        public int InsertarTarima(int codTarima, int codPieza) {
            return base.Channel.InsertarTarima(codTarima, codPieza);
        }
        
        public int ObtenerPiezaInventario(int codPieza) {
            return base.Channel.ObtenerPiezaInventario(codPieza);
        }
        
        public int ActualizarPiezaInventario(int codPieza) {
            return base.Channel.ActualizarPiezaInventario(codPieza);
        }
        
        public int InsertarPiezaInventario(string barras, int planta, int proceso, int configBanco, int consecutivo, int posicion, int articulo, int color, int calidad, int ultimoEstado) {
            return base.Channel.InsertarPiezaInventario(barras, planta, proceso, configBanco, consecutivo, posicion, articulo, color, calidad, ultimoEstado);
        }
        
        public int InsertaPiezaReemplazo(int codPieza, int codProceso, int codPiezaAnterior) {
            return base.Channel.InsertaPiezaReemplazo(codPieza, codProceso, codPiezaAnterior);
        }
        
        public bool ExisteCambioEnProceso(int proceso, int pantalla, System.DateTime fechaUltActualizacion) {
            return base.Channel.ExisteCambioEnProceso(proceso, pantalla, fechaUltActualizacion);
        }
        
        public System.Data.DataSet EnvioDT(System.Data.DataSet dt) {
            return base.Channel.EnvioDT(dt);
        }
        
        public void InsertaError(string parameters, string errorMessage) {
            base.Channel.InsertaError(parameters, errorMessage);
        }
        
        public System.Data.DataTable ObtenerModelos2(int molde) {
            return base.Channel.ObtenerModelos2(molde);
        }
        
        public int ActualizarModeloPieza(int pieza, int modelo) {
            return base.Channel.ActualizarModeloPieza(pieza, modelo);
        }
        
        public int ActualizarCalidadPieza(int pieza, int calidad) {
            return base.Channel.ActualizarCalidadPieza(pieza, calidad);
        }
        
        public System.Data.DataTable ObtenerDefectos(int iProceso) {
            return base.Channel.ObtenerDefectos(iProceso);
        }
        
        public System.Data.DataTable ObtenerZonasDefecto(int iTipoArticulo) {
            return base.Channel.ObtenerZonasDefecto(iTipoArticulo);
        }
        
        public System.Data.DataTable ObtenerEstadosDefecto(int estadoDefecto1, int estadoDefecto2) {
            return base.Channel.ObtenerEstadosDefecto(estadoDefecto1, estadoDefecto2);
        }
        
        public System.Data.DataTable ObtenerCalidades() {
            return base.Channel.ObtenerCalidades();
        }
        
        public int ExisteModelo(string claveArticulo) {
            return base.Channel.ExisteModelo(claveArticulo);
        }
        
        public string ObtenerDesProceso(int proceso) {
            return base.Channel.ObtenerDesProceso(proceso);
        }
        
        public System.Data.DataTable ObtenerTiposModelo() {
            return base.Channel.ObtenerTiposModelo();
        }
        
        public System.Data.DataTable ObtenerModelos(int tipoModelo) {
            return base.Channel.ObtenerModelos(tipoModelo);
        }
        
        public int ExisteModeloHastaRevisado(string claveArticulo) {
            return base.Channel.ExisteModeloHastaRevisado(claveArticulo);
        }
        
        public int ExisteModeloDesdeEsmaltado(string claveArticulo) {
            return base.Channel.ExisteModeloDesdeEsmaltado(claveArticulo);
        }
        
        public int EstaEnInventarioPocesoPieza(string claveArticulo) {
            return base.Channel.EstaEnInventarioPocesoPieza(claveArticulo);
        }
        
        public int ObtenerCodMoldePieza(int iCodPieza) {
            return base.Channel.ObtenerCodMoldePieza(iCodPieza);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerDefectosPiezaProceso(int iCodPieza, int iCodProceso) {
            return base.Channel.ObtenerDefectosPiezaProceso(iCodPieza, iCodProceso);
        }
        
        public int InsertarPieza(int iCodPlanta, string sCodBarras, int iCodConfigBanco, int iCodConsecutivo, int iPosicion, int iCodArticulo, int iCodUltimoProceso, int iCodUltimoEstado, System.DateTime fechaRegistro, int iMolde, int iBase) {
            return base.Channel.InsertarPieza(iCodPlanta, sCodBarras, iCodConfigBanco, iCodConsecutivo, iPosicion, iCodArticulo, iCodUltimoProceso, iCodUltimoEstado, fechaRegistro, iMolde, iBase);
        }
        
        public long InsertarPiezaTransaccion(long lCodConfigHandheld, int iCodPieza, System.DateTime dtFechaRegistro) {
            return base.Channel.InsertarPiezaTransaccion(lCodConfigHandheld, iCodPieza, dtFechaRegistro);
        }
        
        public int ActulizarUltimoProcesoPieza(int iCodPieza, int iCodUltimoProceso) {
            return base.Channel.ActulizarUltimoProcesoPieza(iCodPieza, iCodUltimoProceso);
        }
        
        public int EliminarCarro(int iCodPlanta, int iCodProceso, int iCodCarro) {
            return base.Channel.EliminarCarro(iCodPlanta, iCodProceso, iCodCarro);
        }
        
        public int ActualizarConfigHandHeld(long lCodConfigHandHeld, int iCodSupervisor, int iCodOperador, int iCodConfigBanco) {
            return base.Channel.ActualizarConfigHandHeld(lCodConfigHandHeld, iCodSupervisor, iCodOperador, iCodConfigBanco);
        }
        
        public int InsertarCarroPieza(int iCodPlanta, int iCodProceso, int iCodCarro, int iCodPieza, System.DateTime dFechaRegistro) {
            return base.Channel.InsertarCarroPieza(iCodPlanta, iCodProceso, iCodCarro, iCodPieza, dFechaRegistro);
        }
        
        public int InsertarPiezaTransaccionSecador(long lCodPiezaTransaccion, System.DateTime dtHoraInicio, double dHorasSecado) {
            return base.Channel.InsertarPiezaTransaccionSecador(lCodPiezaTransaccion, dtHoraInicio, dHorasSecado);
        }
        
        public int ActualizarColorPieza(int iCodPieza, int iCodColor) {
            return base.Channel.ActualizarColorPieza(iCodPieza, iCodColor);
        }
        
        public int InsertarCarroZonaPieza(int iCodPlanta, int iCodPieza, int iCodCarro, string sCodZona) {
            return base.Channel.InsertarCarroZonaPieza(iCodPlanta, iCodPieza, iCodCarro, sCodZona);
        }
        
        public int InsertarPiezaDefecto(int iCodPieza, int iCodProceso, int iCodDefecto, int iCodZonaDefecto, int iCodEstadoDefecto, int iCodEmpleado, System.DateTime dtFechaUltimoMovimiento, System.DateTime dtFechaRegistro) {
            return base.Channel.InsertarPiezaDefecto(iCodPieza, iCodProceso, iCodDefecto, iCodZonaDefecto, iCodEstadoDefecto, iCodEmpleado, dtFechaUltimoMovimiento, dtFechaRegistro);
        }
        
        public int EliminarPiezaDefecto(int iCodPieza, int iCodProceso, int iCodDefecto, int iCodZonaDefecto) {
            return base.Channel.EliminarPiezaDefecto(iCodPieza, iCodProceso, iCodDefecto, iCodZonaDefecto);
        }
        
        public int ActualizarPiezaDefecto(int iCodPieza, int iCodProceso, int iCodDefecto, int iCodZonaDefecto, int iCodEstadoDefecto, int iCodEmpleado, System.DateTime dtFechaUltimoMovimiento) {
            return base.Channel.ActualizarPiezaDefecto(iCodPieza, iCodProceso, iCodDefecto, iCodZonaDefecto, iCodEstadoDefecto, iCodEmpleado, dtFechaUltimoMovimiento);
        }
        
        public int ActualizarPiezaUltimoEstado(int iCodPieza, int iCodUltimoEstado) {
            return base.Channel.ActualizarPiezaUltimoEstado(iCodPieza, iCodUltimoEstado);
        }
        
        public int ActualizarPiezaAuditada(int iCodPieza, bool bAuditada) {
            return base.Channel.ActualizarPiezaAuditada(iCodPieza, bAuditada);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerPiezasTarima(int iCodTarima) {
            return base.Channel.ObtenerPiezasTarima(iCodTarima);
        }
        
        public int RechazarTarimaPieza(int iCodTarima) {
            return base.Channel.RechazarTarimaPieza(iCodTarima);
        }
        
        public int ActualizarTarimaPaletizado(int iCodTarima, bool bPaletizado) {
            return base.Channel.ActualizarTarimaPaletizado(iCodTarima, bPaletizado);
        }
        
        public int ExistePiezaEnTarima(int iPieza) {
            return base.Channel.ExistePiezaEnTarima(iPieza);
        }
        
        public int InsertarTarimaPieza(int iTarima, int iPieza, bool iPaletizado, bool iRechazado, System.DateTime FechaRegistro) {
            return base.Channel.InsertarTarimaPieza(iTarima, iPieza, iPaletizado, iRechazado, FechaRegistro);
        }
        
        public int InsertarEtiquetaReemplazo(int iCodPlanta, string sCodBarras, int iCodModelo, int iCodColor, int iCodCalidad, int iCodUltimoProceso, int iCodUltimoEstado, long lCodConfigHandheld, System.DateTime dtFechaRegistro, int iCodProcesoPiezaReem) {
            return base.Channel.InsertarEtiquetaReemplazo(iCodPlanta, sCodBarras, iCodModelo, iCodColor, iCodCalidad, iCodUltimoProceso, iCodUltimoEstado, lCodConfigHandheld, dtFechaRegistro, iCodProcesoPiezaReem);
        }
        
        public System.DateTime ObtenerFechaDepuracionHistoria() {
            return base.Channel.ObtenerFechaDepuracionHistoria();
        }
        
        public System.DateTime ObtenerFechaDepuracionHistoria2(int iCodigoPlanta, int iCodigoProceso) {
            return base.Channel.ObtenerFechaDepuracionHistoria2(iCodigoPlanta, iCodigoProceso);
        }
        
        public System.Data.DataSet SyncServHH(string NombreSPTabla, System.DateTime fechaIns, System.DateTime fechaUpd, System.DateTime fechaDel) {
            return base.Channel.SyncServHH(NombreSPTabla, fechaIns, fechaUpd, fechaDel);
        }
        
        public System.Data.DataSet ActualizarCatalogos(string tabla, int planta, int proceso, System.DateTime fecha) {
            return base.Channel.ActualizarCatalogos(tabla, planta, proceso, fecha);
        }
        
        public System.Data.DataSet ActualizarCatalogosPorPiezas(System.Data.DataTable piezas, string tabla, int proceso) {
            return base.Channel.ActualizarCatalogosPorPiezas(piezas, tabla, proceso);
        }
        
        public System.Data.DataSet ActualizarTransacciones(string tabla, int planta, int proceso, System.DateTime fecha) {
            return base.Channel.ActualizarTransacciones(tabla, planta, proceso, fecha);
        }
        
        public System.Collections.Generic.List<System.Data.DataSet> SyncServHHLDS(System.DateTime fechaIns, System.DateTime fechaUpd, System.DateTime fechaDel) {
            return base.Channel.SyncServHHLDS(fechaIns, fechaUpd, fechaDel);
        }
        
        public System.Data.DataTable TablasCatalogosHH() {
            return base.Channel.TablasCatalogosHH();
        }
        
        public System.Data.DataTable TablasProcesoHH(int planta, int proceso, int pantalla) {
            return base.Channel.TablasProcesoHH(planta, proceso, pantalla);
        }
        
        public int HHSyncCarroPiezaIns(int codPlanta, int codProceso, int codCarro, int codPieza, int codZona) {
            return base.Channel.HHSyncCarroPiezaIns(codPlanta, codProceso, codCarro, codPieza, codZona);
        }
        
        public bool EstaServicioDisponible() {
            return base.Channel.EstaServicioDisponible();
        }
        
        public System.Data.DataTable ObtenerPlantas() {
            return base.Channel.ObtenerPlantas();
        }
        
        public System.Data.DataTable ObtenerProcesos() {
            return base.Channel.ObtenerProcesos();
        }
        
        public System.Data.DataTable Login(string user, string password) {
            return base.Channel.Login(user, password);
        }
        
        public System.Data.DataTable ObtenerPlantasRol(int iCodRol) {
            return base.Channel.ObtenerPlantasRol(iCodRol);
        }
        
        public System.Data.DataTable ObtenerProcesosPorRol(int Rol) {
            return base.Channel.ObtenerProcesosPorRol(Rol);
        }
        
        public System.Data.DataTable ObtenerTurnos() {
            return base.Channel.ObtenerTurnos();
        }
        
        public System.Data.DataTable ObtenerProcesos2() {
            return base.Channel.ObtenerProcesos2();
        }
        
        public System.Data.DataTable ObtenerPantallasProceso(int iCodProceso) {
            return base.Channel.ObtenerPantallasProceso(iCodProceso);
        }
        
        public long InsertarConfigHandHeld(int iCodUsuario, int iCodOperador, int iCodSupervisor, System.DateTime dtFecha, int iCodTurno, int iCodPlanta, int iCodProceso, int iCodConfigBanco, System.DateTime dtFechaRegistro) {
            return base.Channel.InsertarConfigHandHeld(iCodUsuario, iCodOperador, iCodSupervisor, dtFecha, iCodTurno, iCodPlanta, iCodProceso, iCodConfigBanco, dtFechaRegistro);
        }
        
        public int ExisteInventarioProcesoActivo() {
            return base.Channel.ExisteInventarioProcesoActivo();
        }
        
        public int ObtenerClaveEmpleadoMFG(int empleado) {
            return base.Channel.ObtenerClaveEmpleadoMFG(empleado);
        }
        
        public System.Data.DataTable ObtenerSupervisorPorDefecto(int empleado) {
            return base.Channel.ObtenerSupervisorPorDefecto(empleado);
        }
        
        public int ValidarEmpleadoMFG(int empleadoMFG) {
            return base.Channel.ValidarEmpleadoMFG(empleadoMFG);
        }
        
        public System.Data.DataTable ObtenerCentrosTrabajo(int planta, int proceso) {
            return base.Channel.ObtenerCentrosTrabajo(planta, proceso);
        }
        
        public System.Data.DataTable ObtenerMaquinas(int planta, int proceso, int centroTrabajo) {
            return base.Channel.ObtenerMaquinas(planta, proceso, centroTrabajo);
        }
        
        public System.Data.DataTable ObtenerPosicionesBanco(int configBanco) {
            return base.Channel.ObtenerPosicionesBanco(configBanco);
        }
        
        public System.Data.DataTable ObtenerArticulosMolde(int molde) {
            return base.Channel.ObtenerArticulosMolde(molde);
        }
        
        public System.Data.DataTable ObtenerColores() {
            return base.Channel.ObtenerColores();
        }
        
        public System.Data.DataTable ObtenerPruebas(int planta, int proceso) {
            return base.Channel.ObtenerPruebas(planta, proceso);
        }
        
        public System.Data.DataTable ObtenerPiezaCarroHornos(int planta, int carro) {
            return base.Channel.ObtenerPiezaCarroHornos(planta, carro);
        }
        
        public int ActualizarVaciadasAcumuladas(int iCodConfigBanco) {
            return base.Channel.ActualizarVaciadasAcumuladas(iCodConfigBanco);
        }
        
        public int ObtenerNumPosicionesBanco(int configBanco) {
            return base.Channel.ObtenerNumPosicionesBanco(configBanco);
        }
        
        public bool SuperoLimiteVaciadas(int configBanco) {
            return base.Channel.SuperoLimiteVaciadas(configBanco);
        }
        
        public int ActualizarVaciadasAcumuladas2(int iCodConfigBanco, int cant) {
            return base.Channel.ActualizarVaciadasAcumuladas2(iCodConfigBanco, cant);
        }
        
        public int ObtenerCodPiezaCodBarras(string sCodBarras) {
            return base.Channel.ObtenerCodPiezaCodBarras(sCodBarras);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerEstadoPieza(int iCodPieza) {
            return base.Channel.ObtenerEstadoPieza(iCodPieza);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerUltimoProcesoPieza(int iCodPieza) {
            return base.Channel.ObtenerUltimoProcesoPieza(iCodPieza);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerPiezasCarro(int iCodPlanta, int iCodProceso, int iCodCarro) {
            return base.Channel.ObtenerPiezasCarro(iCodPlanta, iCodProceso, iCodCarro);
        }
        
        public int ObtenerCodModeloPieza(int iCodPieza) {
            return base.Channel.ObtenerCodModeloPieza(iCodPieza);
        }
        
        public int ExistePiezaEnCarro(int iCodPlanta, int iCodProceso, int iCodPieza) {
            return base.Channel.ExistePiezaEnCarro(iCodPlanta, iCodProceso, iCodPieza);
        }
        
        public System.Collections.Generic.List<Common.SolutionEntityFramework.BaseSolutionEntity> ObtenerCalidadPieza(int iCodPieza) {
            return base.Channel.ObtenerCalidadPieza(iCodPieza);
        }
    }
}
