//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3603.
// 
namespace LAMOSA.SCPP.Client.View.HandHeld.svcUsuario {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UsuarioServiceWM", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Empleado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Sesion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Usuario))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Password))]
    public partial class UsuarioServiceManagerWM : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public UsuarioServiceManagerWM() {
            this.Url = "http://192.168.20.5/svcscpp/Lamosa.SCPP.ServiceManager.ClassImpl.UsuarioServiceMa" +
                "nagerWM.svc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Lamosa.SCPP.ServiceManager.Interfaces/IUsuarioServiceManagerWM/Loguear", RequestNamespace="Lamosa.SCPP.ServiceManager.Interfaces", ResponseNamespace="Lamosa.SCPP.ServiceManager.Interfaces", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Loguear([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] object uUsuario, out bool LoguearResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool LoguearResultSpecified) {
            object[] results = this.Invoke("Loguear", new object[] {
                        uUsuario});
            LoguearResult = ((bool)(results[0]));
            LoguearResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLoguear(object uUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Loguear", new object[] {
                        uUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndLoguear(System.IAsyncResult asyncResult, out bool LoguearResult, out bool LoguearResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            LoguearResult = ((bool)(results[0]));
            LoguearResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Lamosa.SCPP.ServiceManager.Interfaces/IUsuarioServiceManagerWM/Desloguear", RequestNamespace="Lamosa.SCPP.ServiceManager.Interfaces", ResponseNamespace="Lamosa.SCPP.ServiceManager.Interfaces", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Desloguear([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] object uUsuario, out bool DesloguearResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool DesloguearResultSpecified) {
            object[] results = this.Invoke("Desloguear", new object[] {
                        uUsuario});
            DesloguearResult = ((bool)(results[0]));
            DesloguearResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDesloguear(object uUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Desloguear", new object[] {
                        uUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndDesloguear(System.IAsyncResult asyncResult, out bool DesloguearResult, out bool DesloguearResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            DesloguearResult = ((bool)(results[0]));
            DesloguearResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Lamosa.SCPP.ServiceManager.Interfaces/IUsuarioServiceManagerWM/CambiarPassword", RequestNamespace="Lamosa.SCPP.ServiceManager.Interfaces", ResponseNamespace="Lamosa.SCPP.ServiceManager.Interfaces", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CambiarPassword([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] object uUsuario, out bool CambiarPasswordResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool CambiarPasswordResultSpecified) {
            object[] results = this.Invoke("CambiarPassword", new object[] {
                        uUsuario});
            CambiarPasswordResult = ((bool)(results[0]));
            CambiarPasswordResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCambiarPassword(object uUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CambiarPassword", new object[] {
                        uUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCambiarPassword(System.IAsyncResult asyncResult, out bool CambiarPasswordResult, out bool CambiarPasswordResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            CambiarPasswordResult = ((bool)(results[0]));
            CambiarPasswordResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Lamosa.SCPP.ServiceManager.Interfaces/IUsuarioServiceManagerWM/GetSesion", RequestNamespace="Lamosa.SCPP.ServiceManager.Interfaces", ResponseNamespace="Lamosa.SCPP.ServiceManager.Interfaces", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object GetSesion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] object uUsuario) {
            object[] results = this.Invoke("GetSesion", new object[] {
                        uUsuario});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSesion(object uUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSesion", new object[] {
                        uUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public object EndGetSesion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lamosa.SCPP.Common.Entities.ClassImpl")]
    public partial class Empleado {
        
        private string claveField;
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lamosa.SCPP.Common.Entities.ClassImpl")]
    public partial class Sesion {
        
        private int codigoField;
        
        private bool estadoField;
        
        private System.DateTime fechaFinField;
        
        private System.DateTime fechaInicioField;
        
        private object usuarioField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public bool Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lamosa.SCPP.Common.Entities.ClassImpl")]
    public partial class Usuario {
        
        private string claveField;
        
        private int codigoField;
        
        private string descripcionField;
        
        private object empleadoField;
        
        private string nombreField;
        
        private object passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object Empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Lamosa.SCPP.Common.Entities.ClassImpl")]
    public partial class Password {
        
        private string claveField;
        
        private System.DateTime fechaValidaFinalField;
        
        private System.DateTime fechaValidaInicialField;
        
        private int intentosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaValidaFinal {
            get {
                return this.fechaValidaFinalField;
            }
            set {
                this.fechaValidaFinalField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaValidaInicial {
            get {
                return this.fechaValidaInicialField;
            }
            set {
                this.fechaValidaInicialField = value;
            }
        }
        
        /// <remarks/>
        public int Intentos {
            get {
                return this.intentosField;
            }
            set {
                this.intentosField = value;
            }
        }
    }
}
